extends RefCounted
## Données des rouleaux : écoles, raretés, pouvoirs, affinités et synergies.
## Chaque pouvoir : "name" (titre japonais), "sub" (sous-titre français), "when" (déclencheur, en capitales),
## "text" (effet en clair), "stat" (valeur chiffrée). « {v} » / « {w} » : valeurs des tableaux v / w
## (sur la carte : niveau actuel → niveau suivant ; dans le récapitulatif : niveau actuel).
## Clés facultatives : "max" (niveau max, 3 par défaut, 1 pour les légendaires), "kanji" (idéogramme propre),
## "needs" (au moins un de ces pouvoirs déjà pris).

const SCHOOLS := {
	"fire": {"kanji": "火", "color": Color("#D7372B"), "name": "FEU", "word": "Feu"},
	"water": {"kanji": "水", "color": Color("#1F3A5F"), "name": "EAU", "word": "Eau"},
	"bolt": {"kanji": "雷", "color": Color("#C49A45"), "name": "FOUDRE", "word": "Foudre"},
	"wind": {"kanji": "風", "color": Color("#5F8F86"), "name": "VENT", "word": "Vent"},
	"shadow": {"kanji": "影", "color": Color("#3A3846"), "name": "OMBRE", "word": "Ombre"},
	"ink": {"kanji": "墨", "color": Color("#6E5A44"), "name": "ENCRE", "word": "Encre"},
}
const SCHOOL_ORDER := ["fire", "water", "bolt", "wind", "shadow", "ink"]

const RARITIES := {
	"common": {"rank": 0, "name": "COMMUN", "color": Color("#8A8478")},
	"rare": {"rank": 1, "name": "RARE", "color": Color("#3D78B8")},
	"epic": {"rank": 2, "name": "ÉPIQUE", "color": Color("#8752B5")},
	"legendary": {"rank": 3, "name": "LÉGENDAIRE", "color": Color("#E2A93B")},
}
const RARITY_ORDER := ["common", "rare", "epic", "legendary"]

# seuils d'affinité (nombre de pouvoirs différents d'une école) et leur bonus, en clair
const AFF_TIERS := [2, 4]
const AFFINITY := {
	"fire": ["dégâts de feu +25 %", "dégâts de feu +50 %, chaque coup enflamme"],
	"water": ["+1 bulle d'écume par salle", "+1 cœur à chaque salle, vagues +50 %"],
	"bolt": ["course +10 %, foudre +25 %", "foudre +50 %, éclairs tous les 5 coups"],
	"wind": ["trait max +2 m", "trait max +4 m, course +15 %"],
	"shadow": ["10 % de chances de frapper 2× plus fort", "25 % de chances de frapper 2,5× plus fort"],
}

# petit lexique du récapitulatif : [mot, définition]
const LEXICON := [
	["ÉLAN", "l'encre de ton trait (jauge du bas). Elle remonte quand tu ne traces pas."],
	["CHAÎNE", "traits réussis d'affilée sans être touché : +5 % de dégâts par trait."],
	["FIGURE", "forme tracée (boucle, zigzag, cercle...) qui lance un coup spécial."],
	["AFFINITÉ", "2 puis 4 pouvoirs d'une même école débloquent un bonus d'école."],
]

# [pouvoir, partenaire, effet en plus quand on a les deux] (affiché « Avec <partenaire> : <effet> »)
const SYNERGIES := [
	["shadow_bunshin", "fire_trail", "le clone laisse aussi du feu"],
	["shadow_kitsunebi", "fire_burn", "les feux follets enflamment"],
	["bolt_raijin", "bolt_arc", "+1 ennemi foudroyé par coup"],
	["water_kanagawa", "water_push", "la Grande Vague fait +1 dégât"],
	["fire_kasha", "fire_trail", "la roue de feu laisse du feu"],
	["wind_tsumuji", "wind_feather", "tourbillons +50 % de dégâts"],
	["shadow_execute", "shadow_back", "achève 10 % de vie plus tôt"],
	["wind_fujin", "wind_blades", "l'aspiration blesse aussi"],
	["fire_fudo", "fire_edge", "le halo brûle plus fort"],
	["water_uzushio", "water_tide", "le tourbillon dure 1 s de plus"],
	["bolt_charge", "wind_long", "traits plus longs, plus de charge"],
	["ink_enso", "fire_hearth", "l'onde d'encre enflamme"],
]

const POWERS := {
	# ---------------------------------------------------------------- FEU
	"fire_burn": {"school": "fire", "rarity": "common", "name": "Braise", "sub": "Lame brûlante", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches prend feu et brûle pendant 3 s.",
		"stat": "Brûlure : {v} dégâts/s", "v": [0.5, 0.8, 1.1]},
	"fire_trail": {"school": "fire", "rarity": "common", "name": "Sillage", "sub": "Trait de feu", "when": "À CHAQUE TRAIT",
		"text": "Ton trait laisse une ligne de feu au sol pendant 3 s.",
		"stat": "Feu au sol : {v} dégâts/s", "v": [0.6, 0.9, 1.2]},
	"fire_edge": {"school": "fire", "rarity": "common", "name": "Lame rouge", "sub": "Achever les brûlés", "when": "ENNEMI EN FEU",
		"text": "Tes coups font plus mal aux ennemis qui sont en train de brûler.",
		"stat": "+{v} % de dégâts sur eux", "v": [30, 45, 60], "needs": ["fire_burn", "fire_fudo"]},
	"fire_hearth": {"school": "fire", "rarity": "rare", "name": "Foyer", "sub": "Cercle de feu", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, un cercle de feu explose autour de toi.",
		"stat": "Explosion : {v} dégâts", "v": [1.0, 1.5, 2.0]},
	"fire_spark": {"school": "fire", "rarity": "rare", "name": "Hibana", "sub": "Étincelles", "when": "QUAND UN ENNEMI MEURT",
		"text": "Un ennemi qui meurt en brûlant explose et enflamme ses voisins.",
		"stat": "Explosion : {v} dégâts", "v": [0.6, 0.9, 1.2], "needs": ["fire_burn", "fire_fudo"]},
	"fire_kasha": {"school": "fire", "rarity": "epic", "name": "Kasha", "sub": "Roue de feu", "when": "FIGURE : BOUCLE",
		"text": "Trace une boucle : une roue de feu en sort et fonce sur les ennemis.",
		"stat": "Roue de feu : {v} dégâts/s", "v": [1.5, 2.0, 2.5]},
	"fire_fudo": {"school": "fire", "rarity": "legendary", "name": "Fudō Myōō", "sub": "Halo de flammes", "kanji": "炎", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Un halo de flammes t'entoure et enflamme tout ennemi qui s'approche.",
		"stat": "Halo : {v} dégâts/s", "v": [2.0]},
	"fire_hoo": {"school": "fire", "rarity": "legendary", "name": "Hōō", "sub": "Phénix", "kanji": "鳳", "max": 1,
		"when": "1 FOIS PAR PARTIE",
		"text": "+1 cœur max. Un coup mortel ne te tue pas : tu renais dans une explosion de feu.",
		"stat": "Renais avec {v} cœurs, puis dégâts +25 %", "v": [3]},

	# ---------------------------------------------------------------- EAU
	"water_push": {"school": "water", "rarity": "common", "name": "Ressac", "sub": "Vague qui repousse", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches est projeté loin de ton trait.",
		"stat": "Recul : {v} m", "v": [2.5, 3.2, 4.0]},
	"water_dew": {"school": "water", "rarity": "common", "name": "Rosée", "sub": "Soin par les victoires", "when": "EN TUANT",
		"text": "Tuer des ennemis te soigne : 1 cœur rendu à chaque série.",
		"stat": "+1 cœur tous les {v} ennemis tués", "v": [12, 10, 8]},
	"water_foam": {"school": "water", "rarity": "rare", "name": "Écume", "sub": "Bulle protectrice", "when": "QUAND TU ES TOUCHÉ",
		"text": "Une bulle d'écume encaisse des coups à ta place, puis éclate sur les ennemis.",
		"stat": "Bloque {v}/salle · éclat : {w} dégâts", "v": [1, 1, 2], "w": [1.0, 2.0, 2.0]},
	"water_tide": {"school": "water", "rarity": "rare", "name": "Marée", "sub": "Vague d'arrivée", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, une vague jaillit autour de toi et repousse les ennemis.",
		"stat": "Vague : {v} dégâts", "v": [0.8, 1.2, 1.6]},
	"water_uzushio": {"school": "water", "rarity": "epic", "name": "Uzushio", "sub": "Tourbillon", "kanji": "渦",
		"when": "3 ENNEMIS D'UN TRAIT",
		"text": "Touche 3 ennemis d'un seul trait : un tourbillon s'ouvre à l'arrivée et les aspire.",
		"stat": "Tourbillon (3 s) : {v} dégâts/s", "v": [0.8, 1.1, 1.4]},
	"water_mirror": {"school": "water", "rarity": "epic", "name": "Kagami", "sub": "Miroir d'eau", "kanji": "返",
		"when": "PENDANT TON TRAIT",
		"text": "En courant, tu renvoies sur les ennemis les projectiles que tu frôles.",
		"stat": "Portée du renvoi : {v} m", "v": [1.0, 1.4, 1.8]},
	"water_kanagawa": {"school": "water", "rarity": "legendary", "name": "Kanagawa", "sub": "La Grande Vague", "kanji": "波", "max": 1,
		"when": "TOUS LES 3 TRAITS",
		"text": "Tous les 3 traits, une énorme vague déferle tout le long de ton trait.",
		"stat": "Vague : {v} dégâts · +1 bulle d'écume/salle", "v": [3]},

	# ---------------------------------------------------------------- FOUDRE
	"bolt_arc": {"school": "bolt", "rarity": "common", "name": "Arc", "sub": "Arc électrique", "when": "À CHAQUE COUP",
		"text": "Chaque coup lance un petit éclair sur les ennemis proches de ta cible.",
		"stat": "Cibles en plus : {v} (0,5 dégât)", "v": [1, 2, 3]},
	"bolt_quick": {"school": "bolt", "rarity": "common", "name": "Vif", "sub": "Course éclair", "when": "EN PERMANENCE",
		"text": "Tu cours plus vite le long de ton trait : moins de temps exposé.",
		"stat": "Vitesse de course +{v} %", "v": [20, 30, 40]},
	"bolt_charge": {"school": "bolt", "rarity": "common", "name": "Charge", "sub": "Trait chargé", "when": "QUAND TU ARRIVES",
		"text": "Plus ton trait est long, plus il se charge. À l'arrivée, il foudroie autour de toi.",
		"stat": "{v} dégât par mètre tracé", "v": [0.08, 0.11, 0.14]},
	"bolt_storm": {"school": "bolt", "rarity": "rare", "name": "Orage", "sub": "Foudre du ciel", "when": "TOUS LES {v} COUPS",
		"text": "À force de frapper, la foudre tombe sur les 3 ennemis les plus proches.",
		"stat": "Foudre tous les {v} coups (1 dégât)", "v": [8, 6, 4]},
	"bolt_thunder": {"school": "bolt", "rarity": "rare", "name": "Tonnerre", "sub": "Coup étourdissant", "when": "3 ENNEMIS D'UN TRAIT",
		"text": "Dès le 3e ennemi touché d'un même trait, tes coups étourdissent et frappent plus fort.",
		"stat": "Étourdit · +{v} dégât par coup", "v": [0.4, 0.7, 1.0]},
	"bolt_raiju": {"school": "bolt", "rarity": "epic", "name": "Raijū", "sub": "Loup-tonnerre", "when": "TOUTES LES {v} SECONDES",
		"text": "Un loup de foudre te suit et frappe l'ennemi le plus proche en l'étourdissant.",
		"stat": "Toutes les {v} s : 2 dégâts", "v": [6, 5, 4]},
	"bolt_inazuma": {"school": "bolt", "rarity": "epic", "name": "Inazuma", "sub": "Éclair en chaîne", "when": "FIGURE : ZIGZAG",
		"text": "Ton zigzag foudroie déjà 4 ennemis : l'éclair continue sur d'autres et les étourdit.",
		"stat": "+{v} ennemis foudroyés", "v": [3, 5, 7]},
	"bolt_raijin": {"school": "bolt", "rarity": "legendary", "name": "Raijin no Taiko", "sub": "Tambour du tonnerre", "kanji": "神", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque coup foudroie 2 ennemis. Tous les 4 traits, un tambour frappe les attaquants.",
		"stat": "Éclairs : {v} ennemis · tambour : 2 dégâts", "v": [2]},

	# ---------------------------------------------------------------- VENT
	"wind_long": {"school": "wind", "rarity": "common", "name": "Souffle long", "sub": "Plus d'encre", "when": "EN PERMANENCE",
		"text": "Ta jauge d'élan (l'encre de ton trait) s'allonge : tu traces plus loin.",
		"stat": "Trait max +{v} m", "v": [3, 5, 7]},
	"wind_gust": {"school": "wind", "rarity": "common", "name": "Bourrasque", "sub": "Encre rapide", "when": "EN PERMANENCE",
		"text": "Ton élan (l'encre de ton trait) remonte plus vite quand tu ne traces pas.",
		"stat": "Recharge de l'encre +{v} %", "v": [30, 45, 60]},
	"wind_feather": {"school": "wind", "rarity": "common", "name": "Plume", "sub": "Esquive légère", "when": "EN ESQUIVANT",
		"text": "Ton esquive (petit coup de doigt) ne coûte plus d'encre et va plus loin.",
		"stat": "Bond de {v} m, gratuit", "v": [3.2, 3.6, 4.0]},
	"wind_blades": {"school": "wind", "rarity": "rare", "name": "Kamaitachi", "sub": "Lames de vent", "when": "PENDANT TON TRAIT",
		"text": "Pendant que tu cours, des lames de vent tranchent les ennemis à côté de toi.",
		"stat": "Lames : {v} dégâts", "v": [0.5, 0.8, 1.1]},
	"wind_tsumuji": {"school": "wind", "rarity": "epic", "name": "Tsumuji", "sub": "Tourbillons d'esquive", "when": "EN ESQUIVANT",
		"text": "Chaque esquive laisse un tourbillon tranchant à ton départ et à ton arrivée.",
		"stat": "Tourbillons : {v} dégâts", "v": [1.2, 1.6, 2.0]},
	"wind_stillness": {"school": "wind", "rarity": "epic", "name": "Souffle suspendu", "sub": "Temps ralenti", "when": "EN POSANT LE DOIGT",
		"text": "Poser le doigt pour tracer ralentit le temps un instant (recharge : 5 s).",
		"stat": "Ralenti : {v} s", "v": [0.6, 0.8, 1.0]},
	"wind_fujin": {"school": "wind", "rarity": "legendary", "name": "Fūjin", "sub": "Dieu du vent", "kanji": "嵐", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Ton trait aspire les ennemis proches sur sa ligne, puis ton arrivée les souffle.",
		"stat": "Trait max +{v} m · encre +50 %", "v": [4]},

	# ---------------------------------------------------------------- OMBRE
	"shadow_back": {"school": "shadow", "rarity": "common", "name": "Ushiro", "sub": "Frappe dans le dos", "when": "DANS LE DOS",
		"text": "Frappe un ennemi dans le dos : tes dégâts sont multipliés.",
		"stat": "Dégâts ×{v} dans le dos", "v": [2.0, 2.5, 3.0]},
	"shadow_step": {"school": "shadow", "rarity": "common", "name": "Pas d'ombre", "sub": "Esquive fantôme", "when": "EN ESQUIVANT",
		"text": "Après une esquive, rien ne peut te toucher pendant un court instant.",
		"stat": "Invincible {v} s", "v": [0.5, 0.8, 1.1]},
	"shadow_veil": {"school": "shadow", "rarity": "common", "name": "Voile", "sub": "Voile d'ombre", "when": "2 TUÉS D'UN TRAIT",
		"text": "Tue 2 ennemis ou plus d'un seul trait : tu deviens invincible un instant.",
		"stat": "Invincible {v} s", "v": [0.6, 0.9, 1.2]},
	"shadow_execute": {"school": "shadow", "rarity": "rare", "name": "Kaishaku", "sub": "Coup de grâce", "kanji": "斬",
		"when": "ENNEMI AFFAIBLI",
		"text": "Un ennemi presque mort est achevé net, d'un seul coup.",
		"stat": "Achève sous {v} % de vie", "v": [20, 25, 30]},
	"shadow_utsusemi": {"school": "shadow", "rarity": "epic", "name": "Utsusemi", "sub": "Leurre d'ombre", "kanji": "逃",
		"when": "QUAND TU ES TOUCHÉ",
		"text": "Les premiers coups reçus par salle ne touchent qu'un leurre d'ombre, qui riposte.",
		"stat": "Évite {v}/salle · riposte : {w} dégâts", "v": [1, 1, 2], "w": [1.5, 2.5, 2.5]},
	"shadow_stolen": {"school": "shadow", "rarity": "epic", "name": "Instant volé", "sub": "Ralenti", "when": "4 ENNEMIS D'UN TRAIT",
		"text": "Touche 4 ennemis d'un seul trait : le temps ralentit, vise bien le suivant.",
		"stat": "Ralenti : {v} s", "v": [0.8, 1.0, 1.2]},
	"shadow_bunshin": {"school": "shadow", "rarity": "legendary", "name": "Kage Bunshin", "sub": "Clone d'ombre", "kanji": "幻", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Un clone d'ombre refait chacun de tes traits juste après toi et frappe aussi.",
		"stat": "Clone : 1,2 dégât par ennemi touché", "v": [1]},
	"shadow_kitsunebi": {"school": "shadow", "rarity": "legendary", "name": "Kitsunebi", "sub": "Feux de renard", "kanji": "狐", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Trois feux follets tournent autour de toi et brûlent les ennemis qu'ils touchent.",
		"stat": "{v} feux · 1 dégât par contact", "v": [3]},

	# ---------------------------------------------------------------- ENCRE (sans école)
	"ink_daruma": {"school": "ink", "rarity": "common", "name": "Daruma", "sub": "Porte-bonheur", "when": "TOUT DE SUITE",
		"text": "Gagne 1 cœur max et soigne-toi tout de suite.",
		"stat": "+1 cœur max · soin : {v}", "v": [1, 1, 2]},
	"ink_omamori": {"school": "ink", "rarity": "rare", "name": "Omamori", "sub": "Talisman de chance", "when": "AUX ROULEAUX",
		"text": "Les rouleaux rares, épiques et légendaires sortent plus souvent.",
		"stat": "Chance +{v} % · +1 relance", "v": [30, 60, 90]},
	"ink_rakkan": {"school": "ink", "rarity": "epic", "name": "Rakkan", "sub": "Sceau du maître", "max": 1, "when": "BONUS D'ÉCOLE",
		"text": "Chaque école déjà commencée compte 1 pouvoir de plus pour ses bonus.",
		"stat": "+{v} pouvoir par école commencée", "v": [1]},
	"ink_enso": {"school": "ink", "rarity": "legendary", "name": "Ensō parfait", "sub": "Cercle parfait", "kanji": "円", "max": 1,
		"when": "À CHAQUE FIGURE",
		"text": "Chaque figure lance une onde d'encre. L'ensō (cercle) frappe plus fort et soigne.",
		"stat": "Onde : 1,5 dégât · ensō : {v} dégâts", "v": [2]},
	"ink_ippitsu": {"school": "ink", "rarity": "legendary", "name": "Ippitsu", "sub": "Un seul trait", "kanji": "筆", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque ennemi de plus touché d'un même trait prend plus cher. À 4 : trait suivant ×2.",
		"stat": "+{v} % par ennemi enchaîné", "v": [25]},
}
