extends RefCounted
## Données des rouleaux : écoles, raretés, pouvoirs, affinités et synergies.
## Chaque pouvoir : "name" (titre japonais), "sub" (sous-titre français), "when" (déclencheur, en capitales),
## "text" (effet en clair), "stat" (valeur chiffrée). « {v} » / « {w} » : valeurs des tableaux v / w
## (sur la carte : niveau actuel → niveau suivant ; dans le récapitulatif : niveau actuel).
## Affichage : "label" (nom court français, plus affiché en jeu depuis le retrait de la colonne du HUD), "short" (effet en une ligne pour la carte),
## "icon" (pictogramme UiKit.glyph), "trig" (pictogramme du déclencheur : hit, stroke, arrive, kill…).
## Clés facultatives : "max" (niveau max, 3 par défaut, 1 pour les légendaires), "kanji" (idéogramme propre),
## "needs" (au moins un de ces pouvoirs déjà pris).
## "unlock" : palier de progression (0 = dès le départ ; N = monde N vaincu, voir meta.power_unlocked).
## Les légendaires des sceaux de l'Atelier (meta.SEAL_ITEMS) ne dépendent que de leur sceau.
## École « fig » (figures) : une figure tracée donne seulement +1 chaîne et +15 % de dégâts sur sa ruée ;
## son premier rouleau (FIG_UNLOCK) débloque la technique, les suivants l'améliorent (needs).

const SCHOOLS := {
	"fire": {"kanji": "火", "color": Color("#D7372B"), "name": "FEU", "word": "Feu"},
	"water": {"kanji": "水", "color": Color("#1F3A5F"), "name": "EAU", "word": "Eau"},
	"bolt": {"kanji": "雷", "color": Color("#C49A45"), "name": "FOUDRE", "word": "Foudre"},
	"wind": {"kanji": "風", "color": Color("#5F8F86"), "name": "VENT", "word": "Vent"},
	"shadow": {"kanji": "影", "color": Color("#3A3846"), "name": "OMBRE", "word": "Ombre"},
	"ink": {"kanji": "墨", "color": Color("#6E5A44"), "name": "ENCRE", "word": "Encre"},
	"fig": {"kanji": "法", "color": Color("#A8436B"), "name": "FIGURE", "word": "Figure"},
}
const SCHOOL_ORDER := ["fig", "fire", "water", "bolt", "wind", "shadow", "ink"]

# figure -> rouleau qui débloque sa technique
const FIG_UNLOCK := {"loop": "fig_loop", "zigzag": "fig_zigzag", "straight": "fig_straight",
	"return": "fig_return", "enso": "fig_enso", "hook": "fig_hook"}
# saveur d'école des techniques (2 pouvoirs d'une école suffisent) : effet en deux mots
const FIG_ELEMENT := {"fire": "brûle", "water": "repousse", "bolt": "électrise", "wind": "portée +25 %", "shadow": "dégâts +25 %"}

const RARITIES := {
	"common": {"rank": 0, "name": "COMMUN", "color": Color("#8A8478")},
	"rare": {"rank": 1, "name": "RARE", "color": Color("#3D78B8")},
	"epic": {"rank": 2, "name": "ÉPIQUE", "color": Color("#8752B5")},
	"legendary": {"rank": 3, "name": "LÉGENDAIRE", "color": Color("#E2A93B")},
}
const RARITY_ORDER := ["common", "rare", "epic", "legendary"]

# paliers de rouleaux (champ « unlock ») : nom de la famille débloquée, palier max
const UNLOCK_MAX := 4
const UNLOCK_NAMES := ["Rouleaux de base", "Rouleaux de l'élève", "Rouleaux épiques", "Rouleaux du maître", "Rouleaux légendaires"]


## Palier de progression d'un pouvoir (0 si inconnu).
static func unlock_tier(id: String) -> int:
	var d: Dictionary = POWERS.get(id, {})
	return int(d.get("unlock", 0))


# seuils d'affinité (nombre de pouvoirs différents d'une école) et leur bonus, en clair
const AFF_TIERS := [2, 4]
const AFFINITY := {
	"fire": ["dégâts de feu +25 %", "dégâts de feu +50 %, chaque coup enflamme"],
	"water": ["+1 bulle d'écume par combat", "+1 cœur à chaque combat, vagues +50 %"],
	"bolt": ["course +10 %, foudre +25 %", "foudre +50 %, éclairs tous les 5 coups"],
	"wind": ["trait max +2 m", "trait max +4 m, course +15 %"],
	"shadow": ["10 % de chances de frapper 2× plus fort", "25 % de chances de frapper 2,5× plus fort"],
}
# les mêmes bonus en deux mots (cartes de rouleau)
const AFF_SHORT := {
	"fire": ["Feu +25 %", "Feu +50 %"],
	"water": ["+1 bulle", "+1 cœur/combat"],
	"bolt": ["Foudre +25 %", "Foudre +50 %"],
	"wind": ["Trait +2 m", "Trait +4 m"],
	"shadow": ["Critique ×2", "Critique ×2,5"],
}

# [pouvoir, partenaire, effet en plus quand on a les deux] (affiché « Avec <partenaire> : <effet> »)
const SYNERGIES := [
	["shadow_bunshin", "fire_trail", "le clone laisse aussi du feu"],
	["shadow_kitsunebi", "fire_burn", "les feux follets enflamment"],
	["bolt_raijin", "bolt_arc", "+1 ennemi foudroyé par coup"],
	["water_kanagawa", "water_push", "la Grande Vague fait +1 dégât"],
	["fire_kasha", "fire_trail", "la roue de feu laisse du feu"],
	["wind_tsumuji", "wind_feather", "tourbillons +50 % de dégâts"],
	["shadow_execute", "shadow_back", "achève 10 % de vie plus tôt"],
	["wind_fujin", "wind_blades", "l'aspiration blesse aussi"],
	["fire_fudo", "fire_edge", "le halo brûle plus fort"],
	["water_uzushio", "water_tide", "le tourbillon dure 1 s de plus"],
	["bolt_charge", "wind_long", "traits plus longs, plus de charge"],
	["ink_enso", "fire_hearth", "l'onde d'encre enflamme"],
]

const POWERS := {
	# ---------------------------------------------------------------- FEU
	"fire_burn": {"school": "fire", "rarity": "common", "unlock": 0, "label": "Braise", "short": "Tes coups brûlent : {v}/s", "icon": "blade_fire", "trig": "hit",
		"name": "Braise", "sub": "Lame brûlante", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches prend feu et brûle pendant 3 s.",
		"stat": "Brûlure : {v} dégâts/s", "v": [0.5, 0.8, 1.1]},
	"fire_trail": {"school": "fire", "rarity": "common", "unlock": 0, "label": "Sillage", "short": "Ligne de feu au sol : {v}/s", "icon": "trail_fire", "trig": "stroke",
		"name": "Sillage", "sub": "Trait de feu", "when": "À CHAQUE TRAIT",
		"text": "Ton trait laisse une ligne de feu au sol pendant 3 s.",
		"stat": "Feu au sol : {v} dégâts/s", "v": [0.6, 0.9, 1.2]},
	"fire_edge": {"school": "fire", "rarity": "common", "unlock": 1, "label": "Lame rouge", "short": "+{v} % sur les ennemis en feu", "icon": "claws_fire", "trig": "target",
		"name": "Lame rouge", "sub": "Achever les brûlés", "when": "ENNEMI EN FEU",
		"text": "Tes coups font plus mal aux ennemis qui sont en train de brûler.",
		"stat": "+{v} % de dégâts sur eux", "v": [30, 45, 60], "needs": ["fire_burn", "fire_fudo"]},
	"fire_hearth": {"school": "fire", "rarity": "rare", "unlock": 0, "label": "Foyer", "short": "Explosion à l'arrivée : {v}", "icon": "ring_fire", "trig": "arrive",
		"name": "Foyer", "sub": "Cercle de feu", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, un cercle de feu explose autour de toi.",
		"stat": "Explosion : {v} dégâts", "v": [1.0, 1.5, 2.0]},
	"fire_spark": {"school": "fire", "rarity": "rare", "unlock": 1, "label": "Étincelles", "short": "Brûlé tué : il explose ({v})", "icon": "spark", "trig": "kill",
		"name": "Hibana", "sub": "Étincelles", "when": "QUAND UN ENNEMI MEURT",
		"text": "Un ennemi qui meurt en brûlant explose et enflamme ses voisins.",
		"stat": "Explosion : {v} dégâts", "v": [0.6, 0.9, 1.2], "needs": ["fire_burn", "fire_fudo"]},
	"fire_kasha": {"school": "fire", "rarity": "epic", "unlock": 2, "label": "Roue de feu", "short": "Toupie : roue de feu {v}/s", "icon": "wheel_fire", "trig": "figure",
		"name": "Kasha", "sub": "Roue de feu", "when": "TECHNIQUE : TOUPIE",
		"text": "Ta toupie (boucle) lance une roue de feu qui fonce sur les ennemis.",
		"stat": "Roue de feu : {v} dégâts/s", "v": [1.5, 2.0, 2.5], "needs": ["fig_loop"]},
	"fire_fudo": {"school": "fire", "rarity": "legendary", "unlock": 3, "label": "Halo de feu", "short": "Halo brûlant : {v}/s", "icon": "halo_fire", "trig": "always",
		"name": "Fudō Myōō", "sub": "Halo de flammes", "kanji": "炎", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Un halo de flammes t'entoure et enflamme tout ennemi qui s'approche.",
		"stat": "Halo : {v} dégâts/s", "v": [2.0]},
	"fire_hoo": {"school": "fire", "rarity": "legendary", "unlock": 4, "label": "Phénix", "short": "Renais 1 fois avec {v} cœurs", "icon": "phoenix", "trig": "once",
		"name": "Hōō", "sub": "Phénix", "kanji": "鳳", "max": 1,
		"when": "1 FOIS PAR PARTIE",
		"text": "+1 cœur max. Un coup mortel ne te tue pas : tu renais dans une explosion de feu.",
		"stat": "Renais avec {v} cœurs, puis dégâts +25 %", "v": [3]},

	# ---------------------------------------------------------------- EAU
	"water_push": {"school": "water", "rarity": "common", "unlock": 0, "label": "Ressac", "short": "Tes coups repoussent de {v} m", "icon": "push_wave", "trig": "hit",
		"name": "Ressac", "sub": "Vague qui repousse", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches est projeté loin de ton trait.",
		"stat": "Recul : {v} m", "v": [2.5, 3.2, 4.0]},
	"water_dew": {"school": "water", "rarity": "common", "unlock": 0, "label": "Rosée", "short": "+1 cœur tous les {v} tués", "icon": "heart_drop", "trig": "kill",
		"name": "Rosée", "sub": "Soin par les victoires", "when": "EN TUANT",
		"text": "Tuer des ennemis te soigne : 1 cœur rendu à chaque série.",
		"stat": "+1 cœur tous les {v} ennemis tués", "v": [12, 10, 8]},
	"water_foam": {"school": "water", "rarity": "rare", "unlock": 1, "label": "Écume", "short": "Bulle : bloque {v} coup/combat", "icon": "shield", "trig": "hurt",
		"name": "Écume", "sub": "Bulle protectrice", "when": "QUAND TU ES TOUCHÉ",
		"text": "Une bulle d'écume encaisse des coups à ta place, puis éclate sur les ennemis.",
		"stat": "Bloque {v}/combat · éclat : {w} dégâts", "v": [1, 1, 2], "w": [1.0, 2.0, 2.0]},
	"water_tide": {"school": "water", "rarity": "rare", "unlock": 0, "label": "Marée", "short": "Vague à l'arrivée : {v}", "icon": "tide", "trig": "arrive",
		"name": "Marée", "sub": "Vague d'arrivée", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, une vague jaillit autour de toi et repousse les ennemis.",
		"stat": "Vague : {v} dégâts", "v": [0.8, 1.2, 1.6]},
	"water_uzushio": {"school": "water", "rarity": "epic", "unlock": 2, "label": "Tourbillon", "short": "3 touchés : tourbillon {v}/s", "icon": "whirl", "trig": "multi",
		"name": "Uzushio", "sub": "Tourbillon", "kanji": "渦",
		"when": "3 ENNEMIS D'UN TRAIT",
		"text": "Touche 3 ennemis d'un seul trait : un tourbillon s'ouvre à l'arrivée et les aspire.",
		"stat": "Tourbillon (3 s) : {v} dégâts/s", "v": [0.8, 1.1, 1.4]},
	"water_mirror": {"school": "water", "rarity": "epic", "unlock": 2, "label": "Miroir", "short": "Renvoie les tirs à {v} m", "icon": "mirror", "trig": "stroke",
		"name": "Kagami", "sub": "Miroir d'eau", "kanji": "返",
		"when": "PENDANT TON TRAIT",
		"text": "En courant, tu renvoies sur les ennemis les projectiles que tu frôles.",
		"stat": "Portée du renvoi : {v} m", "v": [1.0, 1.4, 1.8]},
	"water_kanagawa": {"school": "water", "rarity": "legendary", "unlock": 3, "label": "Grande vague", "short": "Tous les 3 traits : vague {v}", "icon": "great_wave", "trig": "stroke",
		"name": "Kanagawa", "sub": "La Grande Vague", "kanji": "波", "max": 1,
		"when": "TOUS LES 3 TRAITS",
		"text": "Tous les 3 traits, une énorme vague déferle tout le long de ton trait.",
		"stat": "Vague : {v} dégâts · +1 bulle d'écume/combat", "v": [3]},

	# ---------------------------------------------------------------- FOUDRE
	"bolt_arc": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Arc", "short": "Chaque coup : éclair +{v} cible", "icon": "chain_bolt", "trig": "hit",
		"name": "Arc", "sub": "Arc électrique", "when": "À CHAQUE COUP",
		"text": "Chaque coup lance un petit éclair sur les ennemis proches de ta cible.",
		"stat": "Cibles en plus : {v} (0,5 dégât)", "v": [1, 2, 3]},
	"bolt_quick": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Vif", "short": "Course +{v} %", "icon": "speed", "trig": "always",
		"name": "Vif", "sub": "Course éclair", "when": "EN PERMANENCE",
		"text": "Tu cours plus vite le long de ton trait : moins de temps exposé.",
		"stat": "Vitesse de course +{v} %", "v": [20, 30, 40]},
	"bolt_charge": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Charge", "short": "Long trait = foudre : {v}/m", "icon": "battery", "trig": "arrive",
		"name": "Charge", "sub": "Trait chargé", "when": "QUAND TU ARRIVES",
		"text": "Plus ton trait est long, plus il se charge. À l'arrivée, il foudroie autour de toi.",
		"stat": "{v} dégât par mètre tracé", "v": [0.08, 0.11, 0.14]},
	"bolt_storm": {"school": "bolt", "rarity": "rare", "unlock": 1, "label": "Orage", "short": "Foudre tous les {v} coups", "icon": "storm", "trig": "hit",
		"name": "Orage", "sub": "Foudre du ciel", "when": "TOUS LES {v} COUPS",
		"text": "À force de frapper, la foudre tombe sur les 3 ennemis les plus proches.",
		"stat": "Foudre tous les {v} coups (1 dégât)", "v": [8, 6, 4]},
	"bolt_thunder": {"school": "bolt", "rarity": "rare", "unlock": 1, "label": "Tonnerre", "short": "3e touché : étourdit, +{v}", "icon": "stun", "trig": "multi",
		"name": "Tonnerre", "sub": "Coup étourdissant", "when": "3 ENNEMIS D'UN TRAIT",
		"text": "Dès le 3e ennemi touché d'un même trait, tes coups étourdissent et frappent plus fort.",
		"stat": "Étourdit · +{v} dégât par coup", "v": [0.4, 0.7, 1.0]},
	"bolt_raiju": {"school": "bolt", "rarity": "epic", "unlock": 2, "label": "Loup foudre", "short": "Un loup frappe toutes les {v} s", "icon": "paw", "trig": "timer",
		"name": "Raijū", "sub": "Loup-tonnerre", "when": "TOUTES LES {v} SECONDES",
		"text": "Un loup de foudre te suit et frappe l'ennemi le plus proche en l'étourdissant.",
		"stat": "Toutes les {v} s : 2 dégâts", "v": [6, 5, 4]},
	"bolt_inazuma": {"school": "bolt", "rarity": "epic", "unlock": 2, "label": "Paralysie", "short": "Éclair : étourdit, +{v}", "icon": "fork_bolt", "trig": "figure",
		"name": "Kanashibari", "sub": "Foudre paralysante", "when": "TECHNIQUE : ÉCLAIR",
		"text": "L'éclair en chaîne de ton zigzag étourdit chaque ennemi qu'il touche et frappe plus fort.",
		"stat": "Étourdit · +{v} dégât par cible", "v": [0.5, 0.8, 1.1], "needs": ["fig_zigzag"]},
	"bolt_raijin": {"school": "bolt", "rarity": "legendary", "unlock": 3, "label": "Tambour", "short": "Chaque coup foudroie {v} ennemis", "icon": "drum", "trig": "hit",
		"name": "Raijin no Taiko", "sub": "Tambour du tonnerre", "kanji": "神", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque coup foudroie 2 ennemis. Tous les 4 traits, un tambour frappe les attaquants.",
		"stat": "Éclairs : {v} ennemis · tambour : 2 dégâts", "v": [2]},

	# ---------------------------------------------------------------- VENT
	"wind_long": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Souffle long", "short": "Trait max +{v} m", "icon": "long_stroke", "trig": "always",
		"name": "Souffle long", "sub": "Plus d'encre", "when": "EN PERMANENCE",
		"text": "Ta jauge d'élan (l'encre de ton trait) s'allonge : tu traces plus loin.",
		"stat": "Trait max +{v} m", "v": [3, 5, 7]},
	"wind_gust": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Bourrasque", "short": "Encre +{v} % plus vite", "icon": "refill", "trig": "always",
		"name": "Bourrasque", "sub": "Encre rapide", "when": "EN PERMANENCE",
		"text": "Ton élan (l'encre de ton trait) remonte plus vite quand tu ne traces pas.",
		"stat": "Recharge de l'encre +{v} %", "v": [30, 45, 60]},
	"wind_feather": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Plume", "short": "Esquive plus longue : {v} m", "icon": "feather", "trig": "dodge",
		"name": "Plume", "sub": "Esquive légère", "when": "EN ESQUIVANT",
		"text": "Ton esquive (un tap) va plus loin.",
		"stat": "Bond de {v} m, gratuit", "v": [3.2, 3.6, 4.0]},
	"wind_blades": {"school": "wind", "rarity": "rare", "unlock": 1, "label": "Lames de vent", "short": "Lames en courant : {v}", "icon": "blades", "trig": "stroke",
		"name": "Kamaitachi", "sub": "Lames de vent", "when": "PENDANT TON TRAIT",
		"text": "Pendant que tu cours, des lames de vent tranchent les ennemis à côté de toi.",
		"stat": "Lames : {v} dégâts", "v": [0.5, 0.8, 1.1]},
	"wind_tsumuji": {"school": "wind", "rarity": "epic", "unlock": 2, "label": "Tornades", "short": "Esquive : tornades {v}", "icon": "tornado", "trig": "dodge",
		"name": "Tsumuji", "sub": "Tourbillons d'esquive", "when": "EN ESQUIVANT",
		"text": "Chaque esquive laisse un tourbillon tranchant à ton départ et à ton arrivée.",
		"stat": "Tourbillons : {v} dégâts", "v": [1.2, 1.6, 2.0]},
	"wind_stillness": {"school": "wind", "rarity": "epic", "unlock": 3, "label": "Ralenti", "short": "Ralenti {v} s en traçant", "icon": "clock", "trig": "touch",
		"name": "Souffle suspendu", "sub": "Temps ralenti", "when": "EN POSANT LE DOIGT",
		"text": "Poser le doigt pour tracer ralentit le temps un instant (recharge : 5 s).",
		"stat": "Ralenti : {v} s", "v": [0.6, 0.8, 1.0]},
	"wind_fujin": {"school": "wind", "rarity": "legendary", "unlock": 4, "label": "Dieu du vent", "short": "Aspire puis souffle · +{v} m", "icon": "cloud_gust", "trig": "stroke",
		"name": "Fūjin", "sub": "Dieu du vent", "kanji": "嵐", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Ton trait aspire les ennemis proches sur sa ligne, puis ton arrivée les souffle.",
		"stat": "Trait max +{v} m · encre +50 %", "v": [4]},

	# ---------------------------------------------------------------- OMBRE
	"shadow_back": {"school": "shadow", "rarity": "common", "unlock": 0, "label": "Dans le dos", "short": "Dans le dos : dégâts ×{v}", "icon": "backstab", "trig": "back",
		"name": "Ushiro", "sub": "Frappe dans le dos", "when": "DANS LE DOS",
		"text": "Frappe un ennemi dans le dos : tes dégâts sont multipliés.",
		"stat": "Dégâts ×{v} dans le dos", "v": [2.0, 2.5, 3.0]},
	"shadow_step": {"school": "shadow", "rarity": "common", "unlock": 0, "label": "Pas d'ombre", "short": "Invincible {v} s après esquive", "icon": "footsteps", "trig": "dodge",
		"name": "Pas d'ombre", "sub": "Esquive fantôme", "when": "EN ESQUIVANT",
		"text": "Après une esquive, rien ne peut te toucher pendant un court instant.",
		"stat": "Invincible {v} s", "v": [0.5, 0.8, 1.1]},
	"shadow_veil": {"school": "shadow", "rarity": "common", "unlock": 1, "label": "Voile", "short": "2 tués d'un trait : invincible {v} s", "icon": "hood", "trig": "kill",
		"name": "Voile", "sub": "Voile d'ombre", "when": "2 TUÉS D'UN TRAIT",
		"text": "Tue 2 ennemis ou plus d'un seul trait : tu deviens invincible un instant.",
		"stat": "Invincible {v} s", "v": [0.6, 0.9, 1.2]},
	"shadow_execute": {"school": "shadow", "rarity": "rare", "unlock": 1, "label": "Coup de grâce", "short": "Achève sous {v} % de vie", "icon": "skull", "trig": "target",
		"name": "Kaishaku", "sub": "Coup de grâce", "kanji": "斬",
		"when": "ENNEMI AFFAIBLI",
		"text": "Un ennemi presque mort est achevé net, d'un seul coup.",
		"stat": "Achève sous {v} % de vie", "v": [20, 25, 30]},
	"shadow_utsusemi": {"school": "shadow", "rarity": "epic", "unlock": 2, "label": "Leurre", "short": "Leurre : évite {v} coup/combat", "icon": "ghost", "trig": "hurt",
		"name": "Utsusemi", "sub": "Leurre d'ombre", "kanji": "逃",
		"when": "QUAND TU ES TOUCHÉ",
		"text": "Les premiers coups reçus par combat ne touchent qu'un leurre d'ombre, qui riposte.",
		"stat": "Évite {v}/combat · riposte : {w} dégâts", "v": [1, 1, 2], "w": [1.5, 2.5, 2.5]},
	"shadow_stolen": {"school": "shadow", "rarity": "epic", "unlock": 3, "label": "Instant volé", "short": "4 touchés : ralenti {v} s", "icon": "hourglass", "trig": "multi",
		"name": "Instant volé", "sub": "Ralenti", "when": "4 ENNEMIS D'UN TRAIT",
		"text": "Touche 4 ennemis d'un seul trait : le temps ralentit, vise bien le suivant.",
		"stat": "Ralenti : {v} s", "v": [0.8, 1.0, 1.2]},
	"shadow_bunshin": {"school": "shadow", "rarity": "legendary", "unlock": 4, "label": "Clone", "short": "Un clone refait tes traits", "icon": "clone", "trig": "stroke",
		"name": "Kage Bunshin", "sub": "Clone d'ombre", "kanji": "幻", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Un clone d'ombre refait chacun de tes traits juste après toi et frappe aussi.",
		"stat": "Clone : 1,2 dégât par ennemi touché", "v": [1]},
	"shadow_kitsunebi": {"school": "shadow", "rarity": "legendary", "unlock": 4, "label": "Feux follets", "short": "{v} feux follets autour de toi", "icon": "fox", "trig": "always",
		"name": "Kitsunebi", "sub": "Feux de renard", "kanji": "狐", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Trois feux follets tournent autour de toi et brûlent les ennemis qu'ils touchent.",
		"stat": "{v} feux · 1 dégât par contact", "v": [3]},

	# ---------------------------------------------------------------- ENCRE (sans école)
	"ink_daruma": {"school": "ink", "rarity": "common", "unlock": 0, "label": "Daruma", "short": "+1 cœur max, soin {v}", "icon": "heart_plus", "trig": "now",
		"name": "Daruma", "sub": "Porte-bonheur", "when": "TOUT DE SUITE",
		"text": "Gagne 1 cœur max et soigne-toi tout de suite.",
		"stat": "+1 cœur max · soin : {v}", "v": [1, 1, 2]},
	"ink_omamori": {"school": "ink", "rarity": "rare", "unlock": 1, "label": "Talisman", "short": "Rouleaux rares +{v} %", "icon": "amulet", "trig": "luck",
		"name": "Omamori", "sub": "Talisman de chance", "when": "AUX ROULEAUX",
		"text": "Les rouleaux rares, épiques et légendaires sortent plus souvent.",
		"stat": "Chance +{v} % · +1 relance", "v": [30, 60, 90]},
	"ink_rakkan": {"school": "ink", "rarity": "epic", "unlock": 3, "label": "Sceau maître", "short": "+{v} pouvoir par école", "icon": "stamp", "trig": "school",
		"name": "Rakkan", "sub": "Sceau du maître", "max": 1, "when": "BONUS D'ÉCOLE",
		"text": "Chaque école déjà commencée compte 1 pouvoir de plus pour ses bonus.",
		"stat": "+{v} pouvoir par école commencée", "v": [1]},
	"ink_enso": {"school": "ink", "rarity": "legendary", "unlock": 4, "label": "Ensō", "short": "Techniques : onde d'encre", "icon": "enso", "trig": "figure",
		"name": "Ensō parfait", "sub": "Cercle parfait", "kanji": "円", "max": 1,
		"when": "À CHAQUE TECHNIQUE",
		"text": "Chaque technique de figure lance une onde d'encre. La frappe au sol laisse un cercle d'encre.",
		"stat": "Onde : 1,5 dégât · frappe au sol : +{v}", "v": [2],
		"needs": ["fig_loop", "fig_zigzag", "fig_straight", "fig_return", "fig_enso", "fig_hook"]},
	"ink_ippitsu": {"school": "ink", "rarity": "legendary", "unlock": 4, "label": "Un seul trait", "short": "+{v} % par ennemi enchaîné", "icon": "one_stroke", "trig": "multi",
		"name": "Ippitsu", "sub": "Un seul trait", "kanji": "筆", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque ennemi de plus touché d'un même trait prend plus cher. À 4 : trait suivant ×2.",
		"stat": "+{v} % par ennemi enchaîné", "v": [25]},

	# ---------------------------------------------------------------- FIGURES (techniques des formes tracées)
	# boucle
	"fig_loop": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Tourbillon", "short": "Boucle : toupie {v}/coup", "icon": "fig_loop", "trig": "figure",
		"name": "Uzu", "sub": "Tourbillon", "kanji": "渦", "when": "FIGURE : BOUCLE",
		"text": "Débloque la toupie : trace une boucle, le héros tourne sur lui-même, aspire et lacère autour de lui.",
		"stat": "Toupie 0,8 s : {v} dégât par coup", "v": [0.45, 0.6, 0.75]},
	"fig_loop_pull": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Tourbillon aspirant", "short": "Toupie : aspire à {v} m", "icon": "fig_loop_pull", "trig": "figure",
		"name": "Uzumaki", "sub": "Tourbillon aspirant", "kanji": "渦", "max": 2, "when": "TECHNIQUE : TOUPIE",
		"text": "Ta toupie dure plus longtemps et aspire les ennemis de plus loin, bien plus fort.",
		"stat": "Aspiration : {v} m · toupie +0,3 s", "v": [4.5, 6.0], "needs": ["fig_loop"]},
	# zigzag
	"fig_zigzag": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Éclair en chaîne", "short": "Zigzag : foudre sur {v} ennemis", "icon": "fig_zigzag", "trig": "figure",
		"name": "Inazuma", "sub": "Éclair en chaîne", "kanji": "雷", "when": "FIGURE : ZIGZAG",
		"text": "Débloque l'éclair : trace un zigzag, ta course accélère et la foudre saute d'ennemi en ennemi.",
		"stat": "Éclair : {v} ennemis, 1 dégât · course ×1,4", "v": [3, 4, 5]},
	"fig_zigzag_long": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Chaîne longue", "short": "Éclair : +{v} cibles", "icon": "fig_zigzag_long", "trig": "figure",
		"name": "Nagare", "sub": "Chaîne longue", "kanji": "雷", "max": 2, "when": "TECHNIQUE : ÉCLAIR",
		"text": "L'éclair de ton zigzag va plus loin et saute sur plus d'ennemis.",
		"stat": "+{v} ennemis foudroyés · portée +3 m", "v": [3, 5], "needs": ["fig_zigzag"]},
	# trait droit
	"fig_straight": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Iaï", "short": "Trait droit : coupe {v}", "icon": "fig_straight", "trig": "figure",
		"name": "Ittō", "sub": "Coupe iaï", "kanji": "一", "when": "FIGURE : TRAIT DROIT",
		"text": "Débloque l'iaï : un long trait droit perce les gardes, puis une coupe tombe sur toute la ligne.",
		"stat": "Coupe : {v} dégâts · course ×1,4", "v": [1.5, 1.8, 2.1]},
	"fig_straight_double": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Double coupe", "short": "Iaï : 2e coupe à {v} %", "icon": "fig_straight_double", "trig": "figure",
		"name": "Nitō", "sub": "Double coupe", "kanji": "一", "max": 2, "when": "TECHNIQUE : IAÏ",
		"text": "Une seconde coupe suit la première, un instant plus tard, sur la même ligne.",
		"stat": "2e coupe : {v} % des dégâts", "v": [60, 90], "needs": ["fig_straight"]},
	"fig_straight_wave": {"school": "fig", "rarity": "epic", "unlock": 2, "label": "Onde tranchante", "short": "Iaï : +{v} m, plus large", "icon": "fig_straight_wave", "trig": "figure",
		"name": "Zankō", "sub": "Onde tranchante", "kanji": "斬", "max": 2, "when": "TECHNIQUE : IAÏ",
		"text": "La coupe file au-delà de ton trait en onde tranchante, plus large et plus loin.",
		"stat": "Coupe prolongée de {v} m · largeur ×1,5", "v": [3, 5], "needs": ["fig_straight"]},
	# aller-retour
	"fig_return": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Garde", "short": "Aller-retour : garde {v} s", "icon": "fig_return", "trig": "figure",
		"name": "Kaeshi", "sub": "Garde", "kanji": "返", "when": "FIGURE : ALLER-RETOUR",
		"text": "Débloque la garde : après un aller-retour, tu te mets en garde et rien ne te touche.",
		"stat": "Garde : {v} s", "v": [0.5, 0.65, 0.8]},
	"fig_return_reflect": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Renvoi", "short": "Renvoie les tirs à {v} m", "icon": "fig_return_reflect", "trig": "figure",
		"name": "Hanekaeshi", "sub": "Renvoi des tirs", "kanji": "返", "max": 2, "when": "TECHNIQUE : GARDE",
		"text": "En traçant ton aller-retour, les tirs proches du trait repartent vers les ennemis.",
		"stat": "Portée du renvoi : {v} m", "v": [1.6, 2.4], "needs": ["fig_return"]},
	"fig_return_counter": {"school": "fig", "rarity": "epic", "unlock": 2, "label": "Contre", "short": "Garde : contre {v}", "icon": "fig_return_counter", "trig": "figure",
		"name": "Ōji", "sub": "Contre", "kanji": "返", "max": 2, "when": "TECHNIQUE : GARDE",
		"text": "Pendant ta garde, chaque ennemi qui prépare un coup près de toi est contré et étourdi.",
		"stat": "Contre : {v} dégâts, étourdit", "v": [2, 3], "needs": ["fig_return"]},
	# ensō
	"fig_enso": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Frappe au sol", "short": "Ensō : bond et onde {v}", "icon": "fig_enso", "trig": "figure",
		"name": "Ensō", "sub": "Frappe au sol", "kanji": "円", "when": "FIGURE : ENSŌ",
		"text": "Débloque la frappe : trace un grand cercle presque fermé, le héros bondit au centre et frappe le sol.",
		"stat": "Onde de choc : {v} dégâts", "v": [1.5, 1.8, 2.1]},
	"fig_enso_big": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Grand ensō", "short": "Ensō : onde +{v} %", "icon": "fig_enso_big", "trig": "figure",
		"name": "Dai-ensō", "sub": "Grand cercle", "kanji": "円", "max": 2, "when": "TECHNIQUE : FRAPPE AU SOL",
		"text": "Ta frappe au sol porte plus loin et projette les ennemis bien plus fort.",
		"stat": "Rayon de l'onde +{v} %", "v": [30, 60], "needs": ["fig_enso"]},
	"fig_enso_heal": {"school": "fig", "rarity": "epic", "unlock": 3, "label": "Ensō de soin", "short": "Ensō : +{v} cœur par combat", "icon": "fig_enso_heal", "trig": "figure",
		"name": "Iyashi", "sub": "Ensō de soin", "kanji": "円", "max": 1, "when": "TECHNIQUE : FRAPPE AU SOL",
		"text": "La première frappe au sol de chaque combat te soigne.",
		"stat": "+{v} cœur, 1 fois par combat", "v": [1], "needs": ["fig_enso"]},
	# crochet
	"fig_hook": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Estoc", "short": "Crochet : estoc {v}", "icon": "fig_hook", "trig": "figure",
		"name": "Kagi", "sub": "Estoc", "kanji": "鉤", "when": "FIGURE : CROCHET",
		"text": "Débloque l'estoc : trace un crochet, le héros fait demi-tour et transperce l'ennemi le plus proche.",
		"stat": "Estoc : {v} dégâts", "v": [2.0, 2.5, 3.0]},
	"fig_hook_back": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Estoc assassin", "short": "Estoc ×{v} : blessé ou de dos", "icon": "fig_hook_back", "trig": "figure",
		"name": "Ansatsu", "sub": "Estoc assassin", "kanji": "背", "max": 2, "when": "TECHNIQUE : ESTOC",
		"text": "Ton estoc frappe bien plus fort un ennemi pris de dos ou déjà à moitié mort.",
		"stat": "Estoc ×{v} (de dos, ou sous 50 % de vie)", "v": [2.0, 2.5], "needs": ["fig_hook"]},
	"fig_hook_double": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Double estoc", "short": "Estoc : +{v} cible", "icon": "fig_hook_double", "trig": "figure",
		"name": "Nidan-zuki", "sub": "Double estoc", "kanji": "鉤", "max": 2, "when": "TECHNIQUE : ESTOC",
		"text": "Ton estoc transperce aussi les ennemis voisins de ta cible.",
		"stat": "+{v} ennemi transpercé", "v": [1, 2], "needs": ["fig_hook"]},
}
