extends RefCounted
## Données des rouleaux : écoles, raretés, pouvoirs, affinités et synergies.
## Chaque pouvoir : "name" (titre japonais), "sub" (sous-titre français), "when" (déclencheur, en capitales),
## "text" (effet en clair), "stat" (valeur chiffrée). « {v} » / « {w} » : valeurs des tableaux v / w
## (sur la carte : niveau actuel → niveau suivant ; dans le récapitulatif : niveau actuel).
## Affichage : "label" (nom court français, plus affiché en jeu depuis le retrait de la colonne du HUD), "short" (effet en une ligne pour la carte),
## "icon" (pictogramme UiKit.glyph), "trig" (pictogramme du déclencheur : hit, stroke, arrive, kill…).
## Clés facultatives : "max" (niveau max, 3 par défaut, 1 pour les légendaires), "kanji" (idéogramme propre),
## "needs" (au moins un de ces pouvoirs déjà pris).
## Effet affiché en pastilles (cartes, bulles, récapitulatif) : EFFECTS, plus bas (pictogramme, chiffre, libellé).
## "unlock" : palier de progression (0 = dès le départ ; N = monde N vaincu, voir meta.power_unlocked).
## Les légendaires des sceaux de l'Atelier (meta.SEAL_ITEMS) ne dépendent que de leur sceau.
## École « fig » (figures) : une figure tracée donne seulement +1 chaîne et +15 % de dégâts sur sa ruée ;
## son premier rouleau (FIG_UNLOCK) débloque la technique, les suivants l'améliorent (needs).

const SCHOOLS := {
	"fire": {"kanji": "火", "color": Color("#D7372B"), "name": "FEU", "word": "Feu"},
	"water": {"kanji": "水", "color": Color("#1F3A5F"), "name": "EAU", "word": "Eau"},
	"bolt": {"kanji": "雷", "color": Color("#C49A45"), "name": "FOUDRE", "word": "Foudre"},
	"wind": {"kanji": "風", "color": Color("#5F8F86"), "name": "VENT", "word": "Vent"},
	"shadow": {"kanji": "影", "color": Color("#3A3846"), "name": "OMBRE", "word": "Ombre"},
	"ink": {"kanji": "墨", "color": Color("#6E5A44"), "name": "ENCRE", "word": "Encre"},
	"fig": {"kanji": "法", "color": Color("#A8436B"), "name": "FIGURE", "word": "Figure"},
}
const SCHOOL_ORDER := ["fig", "fire", "water", "bolt", "wind", "shadow", "ink"]

# figure -> rouleau qui débloque sa technique
const FIG_UNLOCK := {"loop": "fig_loop", "zigzag": "fig_zigzag", "straight": "fig_straight",
	"return": "fig_return", "enso": "fig_enso", "hook": "fig_hook",
	"wave": "fig_wave", "point": "fig_point", "triangle": "fig_triangle"}
# figures de l'arbre (branche Voie) : leurs rouleaux (technique et améliorations) ne sortent que si la figure
# est apprise (meta.fig_learned ; powers._eligible)
const FIG_TREE := ["wave", "point", "triangle"]


## Figure de l'arbre dont dépend ce rouleau (sa technique ou une amélioration), "" sinon.
static func tree_figure(id: String) -> String:
	for f in FIG_TREE:
		var tid := String(FIG_UNLOCK[f])
		if id == tid or id.begins_with(tid + "_"):
			return String(f)
	return ""
# saveur d'école des techniques (2 pouvoirs d'une école suffisent) : effet en deux mots
const FIG_ELEMENT := {"fire": "brûle", "water": "repousse", "bolt": "électrise", "wind": "portée +25 %", "shadow": "dégâts +25 %"}

const RARITIES := {
	"common": {"rank": 0, "name": "COMMUN", "color": Color("#8A8478")},
	"rare": {"rank": 1, "name": "RARE", "color": Color("#3D78B8")},
	"epic": {"rank": 2, "name": "ÉPIQUE", "color": Color("#8752B5")},
	"legendary": {"rank": 3, "name": "LÉGENDAIRE", "color": Color("#E2A93B")},
}
const RARITY_ORDER := ["common", "rare", "epic", "legendary"]

# paliers de rouleaux (champ « unlock ») : nom de la famille débloquée, palier max
const UNLOCK_MAX := 4
const UNLOCK_NAMES := ["Rouleaux de base", "Rouleaux de l'élève", "Rouleaux épiques", "Rouleaux du maître", "Rouleaux légendaires"]


## Palier de progression d'un pouvoir (0 si inconnu).
static func unlock_tier(id: String) -> int:
	var d: Dictionary = POWERS.get(id, {})
	return int(d.get("unlock", 0))


# seuils d'affinité (nombre de pouvoirs différents d'une école) et leur bonus, en clair
const AFF_TIERS := [2, 4]
const AFFINITY := {
	"fire": ["dégâts de feu +25 %", "dégâts de feu +50 %, chaque coup enflamme"],
	"water": ["+1 bulle d'écume par combat", "+1 cœur un combat sur deux, vagues +50 %"],
	"bolt": ["course +10 %, foudre +25 %", "foudre +50 %, éclairs tous les 5 coups"],
	"wind": ["trait max +2 m", "trait max +4 m, course +15 %"],
	"shadow": ["10 % de chances de frapper 2× plus fort", "25 % de chances de frapper 2,5× plus fort"],
}
# les mêmes bonus en deux mots (cartes de rouleau)
const AFF_SHORT := {
	"fire": ["Feu +25 %", "Feu +50 %"],
	"water": ["+1 bulle", "+1 cœur/2 combats"],
	"bolt": ["Foudre +25 %", "Foudre +50 %"],
	"wind": ["Trait +2 m", "Trait +4 m"],
	"shadow": ["Critique ×2", "Critique ×2,5"],
}

# [pouvoir, partenaire, effet en plus quand on a les deux] (affiché « Avec <partenaire> : <effet> »)
const SYNERGIES := [
	["shadow_bunshin", "fire_trail", "le clone laisse aussi du feu"],
	["shadow_kitsunebi", "fire_burn", "les feux follets enflamment"],
	["bolt_raijin", "bolt_arc", "+1 ennemi foudroyé par coup"],
	["water_kanagawa", "water_push", "la Grande Vague fait +1 dégât"],
	["fire_kasha", "fire_trail", "la roue de feu laisse du feu"],
	["wind_tsumuji", "wind_feather", "tourbillons +50 % de dégâts"],
	["shadow_execute", "shadow_back", "achève 10 % de vie plus tôt"],
	["wind_fujin", "wind_blades", "l'aspiration blesse aussi"],
	["fire_fudo", "fire_edge", "le halo brûle plus fort"],
	["water_uzushio", "water_tide", "le tourbillon dure 1 s de plus"],
	["bolt_charge", "wind_long", "traits plus longs, plus de charge"],
	["ink_enso", "fire_hearth", "l'onde d'encre enflamme"],
	["fire_ash", "fire_trail", "les cendres brûlent aussi (0,5/s)"],
	["fire_lantern", "fire_spark", "embrasement : dégâts ×1,5"],
	["water_mist", "water_mirror", "les tirs dissous repartent sur l'ennemi"],
	["bolt_rod", "bolt_arc", "la foudre saute sur +1 ennemi"],
	["bolt_static", "bolt_charge", "nova +50 %"],
	["wind_gale", "water_mirror", "les tirs soufflés repartent sur l'ennemi"],
	["wind_current", "wind_long", "+1 m de poussée"],
	["shadow_double", "shadow_back", "la doublure frappe dans le dos : ×2"],
	["shadow_dusk", "shadow_execute", "le premier coup achève 15 % de vie plus tôt"],
	["ink_thick", "water_tide", "la vague d'arrivée laisse une tache"],
	["ink_seal", "ink_enso", "le sceau laisse un cercle d'encre"],
]

const POWERS := {
	# ---------------------------------------------------------------- FEU
	"fire_burn": {"school": "fire", "rarity": "common", "unlock": 0, "label": "Braise", "short": "Tes coups brûlent : {v}/s", "icon": "blade_fire", "trig": "hit",
		"name": "Braise", "sub": "Lame brûlante", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches prend feu et brûle pendant 3 s.",
		"stat": "Brûlure : {v} dégâts/s", "v": [0.5, 0.8, 1.1]},
	"fire_trail": {"school": "fire", "rarity": "common", "unlock": 0, "label": "Sillage", "short": "Ligne de feu au sol : {v}/s", "icon": "trail_fire", "trig": "stroke",
		"name": "Sillage", "sub": "Trait de feu", "when": "À CHAQUE TRAIT",
		"text": "Ton trait laisse une ligne de feu au sol pendant 3 s.",
		"stat": "Feu au sol : {v} dégâts/s", "v": [0.6, 0.9, 1.2]},
	"fire_edge": {"school": "fire", "rarity": "common", "unlock": 1, "label": "Lame rouge", "short": "+{v} % sur les ennemis en feu", "icon": "claws_fire", "trig": "target",
		"name": "Lame rouge", "sub": "Achever les brûlés", "when": "ENNEMI EN FEU",
		"text": "Tes coups font plus mal aux ennemis qui sont en train de brûler.",
		"stat": "+{v} % de dégâts sur eux", "v": [30, 45, 60], "needs": ["fire_burn", "fire_fudo"]},
	"fire_hearth": {"school": "fire", "rarity": "rare", "unlock": 0, "label": "Foyer", "short": "Explosion à l'arrivée : {v}", "icon": "ring_fire", "trig": "arrive",
		"name": "Foyer", "sub": "Cercle de feu", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, un cercle de feu explose autour de toi.",
		"stat": "Explosion : {v} dégâts", "v": [1.0, 1.5, 2.0]},
	"fire_spark": {"school": "fire", "rarity": "rare", "unlock": 1, "label": "Étincelles", "short": "Brûlé tué : il explose ({v})", "icon": "spark", "trig": "kill",
		"name": "Hibana", "sub": "Étincelles", "when": "QUAND UN ENNEMI MEURT",
		"text": "Un ennemi qui meurt en brûlant explose et enflamme ses voisins.",
		"stat": "Explosion : {v} dégâts", "v": [0.6, 0.9, 1.2], "needs": ["fire_burn", "fire_fudo"]},
	"fire_kasha": {"school": "fire", "rarity": "epic", "unlock": 2, "label": "Roue de feu", "short": "Toupie : roue de feu {v}/s", "icon": "wheel_fire", "trig": "figure",
		"name": "Kasha", "sub": "Roue de feu", "when": "TECHNIQUE : TOUPIE",
		"text": "Ta toupie (boucle) lance une roue de feu qui fonce sur les ennemis.",
		"stat": "Roue de feu : {v} dégâts/s", "v": [1.5, 2.0, 2.5], "needs": ["fig_loop"]},
	"fire_fudo": {"school": "fire", "rarity": "legendary", "unlock": 3, "label": "Halo de feu", "short": "Halo brûlant : {v}/s", "icon": "halo_fire", "trig": "always",
		"name": "Fudō Myōō", "sub": "Halo de flammes", "kanji": "炎", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Un halo de flammes t'entoure et enflamme tout ennemi qui s'approche.",
		"stat": "Halo : {v} dégâts/s", "v": [2.0]},
	"fire_ash": {"school": "fire", "rarity": "common", "unlock": 1, "label": "Cendres", "short": "Brûlé tué : cendres {v} s", "icon": "spark", "trig": "kill",
		"name": "Hai", "sub": "Cendres", "when": "QUAND UN BRÛLÉ MEURT",
		"text": "Un ennemi qui meurt en brûlant laisse un tas de cendres chaudes : les ennemis qui le traversent prennent feu.",
		"stat": "Cendres pendant {v} s", "v": [2.0, 3.0, 4.0], "needs": ["fire_burn", "fire_fudo"]},
	"fire_lantern": {"school": "fire", "rarity": "rare", "unlock": 2, "label": "Lanterne", "short": "Un brûlé s'embrase toutes les {v} s", "icon": "halo_fire", "trig": "timer",
		"name": "Chōchin", "sub": "Lanterne", "when": "TOUTES LES {v} SECONDES",
		"text": "L'ennemi en feu le plus proche s'embrase comme une lanterne : une gerbe de flammes brûle et enflamme ses voisins.",
		"stat": "Toutes les {v} s : gerbe de 0,8 dégât", "v": [5, 4, 3], "needs": ["fire_burn", "fire_fudo"]},
	"fire_hoo": {"school": "fire", "rarity": "legendary", "unlock": 4, "label": "Phénix", "short": "Renais 1 fois avec {v} cœurs", "icon": "phoenix", "trig": "once",
		"name": "Hōō", "sub": "Phénix", "kanji": "鳳", "max": 1,
		"when": "1 FOIS PAR PARTIE",
		"text": "+1 cœur max. Un coup mortel ne te tue pas : tu renais dans une explosion de feu.",
		"stat": "Renais avec {v} cœurs, puis dégâts +25 %", "v": [3]},

	# ---------------------------------------------------------------- EAU
	"water_push": {"school": "water", "rarity": "common", "unlock": 0, "label": "Ressac", "short": "Tes coups repoussent de {v} m", "icon": "push_wave", "trig": "hit",
		"name": "Ressac", "sub": "Vague qui repousse", "when": "À CHAQUE COUP",
		"text": "Chaque ennemi que tu tranches est projeté loin de ton trait.",
		"stat": "Recul : {v} m", "v": [2.5, 3.2, 4.0]},
	"water_dew": {"school": "water", "rarity": "common", "unlock": 0, "label": "Rosée", "short": "+1 cœur tous les {v} tués", "icon": "heart_drop", "trig": "kill",
		"name": "Rosée", "sub": "Soin par les victoires", "when": "EN TUANT",
		"text": "Tuer des ennemis te soigne : 1 cœur rendu à chaque série.",
		"stat": "+1 cœur tous les {v} ennemis tués", "v": [16, 14, 12]},
	"water_foam": {"school": "water", "rarity": "rare", "unlock": 1, "label": "Écume", "short": "Bulle : bloque {v} coup/combat", "icon": "shield", "trig": "hurt",
		"name": "Écume", "sub": "Bulle protectrice", "when": "QUAND TU ES TOUCHÉ",
		"text": "Une bulle d'écume encaisse des coups à ta place, puis éclate sur les ennemis.",
		"stat": "Bloque {v}/combat · éclat : {w} dégâts", "v": [1, 1, 2], "w": [1.0, 2.0, 2.0]},
	"water_tide": {"school": "water", "rarity": "rare", "unlock": 0, "label": "Marée", "short": "Vague à l'arrivée : {v}", "icon": "tide", "trig": "arrive",
		"name": "Marée", "sub": "Vague d'arrivée", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, une vague jaillit autour de toi et repousse les ennemis.",
		"stat": "Vague : {v} dégâts", "v": [0.8, 1.2, 1.6]},
	"water_uzushio": {"school": "water", "rarity": "epic", "unlock": 2, "label": "Tourbillon", "short": "3 touchés : tourbillon {v}/s", "icon": "whirl", "trig": "multi",
		"name": "Uzushio", "sub": "Tourbillon", "kanji": "渦",
		"when": "3 ENNEMIS D'UN TRAIT",
		"text": "Touche 3 ennemis d'un seul trait : un tourbillon s'ouvre à l'arrivée et les aspire.",
		"stat": "Tourbillon (3 s) : {v} dégâts/s", "v": [0.8, 1.1, 1.4]},
	"water_mirror": {"school": "water", "rarity": "epic", "unlock": 2, "label": "Miroir", "short": "Renvoie les tirs à {v} m", "icon": "mirror", "trig": "stroke",
		"name": "Kagami", "sub": "Miroir d'eau", "kanji": "返",
		"when": "PENDANT TON TRAIT",
		"text": "En courant, tu renvoies sur les ennemis les projectiles que tu frôles.",
		"stat": "Portée du renvoi : {v} m", "v": [1.0, 1.4, 1.8]},
	"water_mist": {"school": "water", "rarity": "rare", "unlock": 1, "label": "Brume", "short": "Brume à l'arrivée : {v} s sans tirs", "icon": "cloud_gust", "trig": "arrive",
		"name": "Kiri", "sub": "Brume d'eau", "when": "QUAND TU ARRIVES",
		"text": "À la fin de chaque trait, une brume t'entoure : les tirs qui la traversent se dissolvent.",
		"stat": "Brume pendant {v} s (2,3 m)", "v": [1.5, 2.0, 2.5]},
	"water_spring": {"school": "water", "rarity": "epic", "unlock": 3, "label": "Source", "short": "Arrivée : +1 cœur tous les {v} combats", "icon": "heart_drop", "trig": "arrive",
		"name": "Izumi", "sub": "Source claire", "when": "QUAND TU ARRIVES",
		"text": "Une source jaillit à ton arrivée et te rend 1 cœur, si tu en as perdu : une fois tous les {v} combats.",
		"stat": "+1 cœur tous les {v} combats", "v": [4, 3, 2]},
	"water_kanagawa": {"school": "water", "rarity": "legendary", "unlock": 3, "label": "Grande vague", "short": "Tous les 3 traits : vague {v}", "icon": "great_wave", "trig": "stroke",
		"name": "Kanagawa", "sub": "La Grande Vague", "kanji": "波", "max": 1,
		"when": "TOUS LES 3 TRAITS",
		"text": "Tous les 3 traits, une énorme vague déferle tout le long de ton trait.",
		"stat": "Vague : {v} dégâts · +1 bulle d'écume/combat", "v": [3]},

	# ---------------------------------------------------------------- FOUDRE
	"bolt_arc": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Arc", "short": "Chaque coup : éclair +{v} cible", "icon": "chain_bolt", "trig": "hit",
		"name": "Arc", "sub": "Arc électrique", "when": "À CHAQUE COUP",
		"text": "Chaque coup lance un petit éclair sur les ennemis proches de ta cible.",
		"stat": "Cibles en plus : {v} (0,5 dégât)", "v": [1, 2, 3]},
	"bolt_quick": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Vif", "short": "Course +{v} %", "icon": "speed", "trig": "always",
		"name": "Vif", "sub": "Course éclair", "when": "EN PERMANENCE",
		"text": "Tu cours plus vite le long de ton trait : moins de temps exposé.",
		"stat": "Vitesse de course +{v} %", "v": [20, 30, 40]},
	"bolt_charge": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Charge", "short": "Long trait = foudre : {v}/m", "icon": "battery", "trig": "arrive",
		"name": "Charge", "sub": "Trait chargé", "when": "QUAND TU ARRIVES",
		"text": "Plus ton trait est long, plus il se charge. À l'arrivée, il foudroie autour de toi.",
		"stat": "{v} dégât par mètre tracé", "v": [0.08, 0.11, 0.14]},
	"bolt_storm": {"school": "bolt", "rarity": "rare", "unlock": 1, "label": "Orage", "short": "Foudre tous les {v} coups", "icon": "storm", "trig": "hit",
		"name": "Orage", "sub": "Foudre du ciel", "when": "TOUS LES {v} COUPS",
		"text": "À force de frapper, la foudre tombe sur les 3 ennemis les plus proches.",
		"stat": "Foudre tous les {v} coups (1 dégât)", "v": [8, 6, 4]},
	"bolt_thunder": {"school": "bolt", "rarity": "rare", "unlock": 1, "label": "Tonnerre", "short": "3e touché : étourdit, +{v}", "icon": "stun", "trig": "multi",
		"name": "Tonnerre", "sub": "Coup étourdissant", "when": "3 ENNEMIS D'UN TRAIT",
		"text": "Dès le 3e ennemi touché d'un même trait, tes coups étourdissent et frappent plus fort.",
		"stat": "Étourdit · +{v} dégât par coup", "v": [0.4, 0.7, 1.0]},
	"bolt_raiju": {"school": "bolt", "rarity": "epic", "unlock": 2, "label": "Loup foudre", "short": "Un loup frappe toutes les {v} s", "icon": "paw", "trig": "timer",
		"name": "Raijū", "sub": "Loup-tonnerre", "when": "TOUTES LES {v} SECONDES",
		"text": "Un loup de foudre te suit et frappe l'ennemi le plus proche en l'étourdissant.",
		"stat": "Toutes les {v} s : 2 dégâts", "v": [6, 5, 4]},
	"bolt_inazuma": {"school": "bolt", "rarity": "epic", "unlock": 2, "label": "Paralysie", "short": "Éclair : étourdit, +{v}", "icon": "fork_bolt", "trig": "figure",
		"name": "Kanashibari", "sub": "Foudre paralysante", "when": "TECHNIQUE : ÉCLAIR",
		"text": "L'éclair en chaîne de ton zigzag étourdit chaque ennemi qu'il touche et frappe plus fort.",
		"stat": "Étourdit · +{v} dégât par cible", "v": [0.5, 0.8, 1.1], "needs": ["fig_zigzag"]},
	"bolt_rod": {"school": "bolt", "rarity": "rare", "unlock": 2, "label": "Paratonnerre", "short": "Attaque proche : foudre, recharge {v} s", "icon": "fork_bolt", "trig": "timer",
		"name": "Hiraishin", "sub": "Paratonnerre", "when": "ENNEMI QUI ARME SON COUP",
		"text": "Un ennemi qui prépare un coup à moins de 4 m de toi est foudroyé : son attaque est interrompue.",
		"stat": "Foudre : 1 dégât, étourdit · recharge {v} s", "v": [5, 4, 3]},
	"bolt_static": {"school": "bolt", "rarity": "common", "unlock": 0, "label": "Statique", "short": "4e trait : nova {v}", "icon": "storm", "trig": "stroke",
		"name": "Seidenki", "sub": "Électricité statique", "when": "TOUS LES 4 TRAITS",
		"text": "Chaque trait te charge d'électricité. Le 4e libère une nova autour de ton arrivée, qui étourdit.",
		"stat": "Nova : {v} dégâts à 2,5 m", "v": [1.0, 1.4, 1.8]},
	"bolt_raijin": {"school": "bolt", "rarity": "legendary", "unlock": 3, "label": "Tambour", "short": "Chaque coup foudroie {v} ennemis", "icon": "drum", "trig": "hit",
		"name": "Raijin no Taiko", "sub": "Tambour du tonnerre", "kanji": "神", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque coup foudroie 2 ennemis. Tous les 4 traits, un tambour frappe les attaquants.",
		"stat": "Éclairs : {v} ennemis · tambour : 2 dégâts", "v": [2]},

	# ---------------------------------------------------------------- VENT
	"wind_long": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Souffle long", "short": "Trait max +{v} m", "icon": "long_stroke", "trig": "always",
		"name": "Souffle long", "sub": "Plus d'encre", "when": "EN PERMANENCE",
		"text": "Ta jauge d'élan (l'encre de ton trait) s'allonge : tu traces plus loin.",
		"stat": "Trait max +{v} m", "v": [3, 5, 7]},
	"wind_gust": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Bourrasque", "short": "Encre +{v} % plus vite", "icon": "refill", "trig": "always",
		"name": "Bourrasque", "sub": "Encre rapide", "when": "EN PERMANENCE",
		"text": "Ton élan (l'encre de ton trait) remonte plus vite quand tu ne traces pas.",
		"stat": "Recharge de l'encre +{v} %", "v": [30, 45, 60]},
	"wind_feather": {"school": "wind", "rarity": "common", "unlock": 0, "label": "Plume", "short": "Trait : {v} m sans encre", "icon": "feather", "trig": "stroke",
		"name": "Plume", "sub": "Départ léger", "when": "À CHAQUE TRAIT",
		"text": "Le début de chaque trait ne coûte pas d'encre : les premiers mètres sont offerts.",
		"stat": "{v} premiers mètres gratuits", "v": [1.5, 2.5, 3.5]},
	"wind_blades": {"school": "wind", "rarity": "rare", "unlock": 1, "label": "Lames de vent", "short": "Lames en courant : {v}", "icon": "blades", "trig": "stroke",
		"name": "Kamaitachi", "sub": "Lames de vent", "when": "PENDANT TON TRAIT",
		"text": "Pendant que tu cours, des lames de vent tranchent les ennemis à côté de toi.",
		"stat": "Lames : {v} dégâts", "v": [0.5, 0.8, 1.1]},
	"wind_tsumuji": {"school": "wind", "rarity": "epic", "unlock": 2, "label": "Tornades", "short": "Ruée : tornades {v}", "icon": "tornado", "trig": "stroke",
		"name": "Tsumuji", "sub": "Tourbillons de ruée", "when": "À CHAQUE TRAIT",
		"text": "Chaque ruée laisse un tourbillon tranchant à ton départ, et un autre à ton arrivée.",
		"stat": "Tourbillons : {v} dégâts", "v": [0.8, 1.1, 1.4]},
	"wind_stillness": {"school": "wind", "rarity": "epic", "unlock": 3, "label": "Ralenti", "short": "Ralenti {v} s en traçant", "icon": "clock", "trig": "touch",
		"name": "Souffle suspendu", "sub": "Temps ralenti", "when": "EN POSANT LE DOIGT",
		"text": "Poser le doigt pour tracer ralentit le temps un instant (recharge : 5 s).",
		"stat": "Ralenti : {v} s", "v": [0.6, 0.8, 1.0]},
	"wind_gale": {"school": "wind", "rarity": "common", "unlock": 1, "label": "Rafale", "short": "Ruée : souffle les tirs à {v} m", "icon": "push_wave", "trig": "stroke",
		"name": "Shippū", "sub": "Rafale", "when": "PENDANT TON TRAIT",
		"text": "Pendant ta ruée, les tirs qui passent près de toi sont soufflés au loin.",
		"stat": "Tirs soufflés à {v} m", "v": [1.6, 2.1, 2.6]},
	"wind_current": {"school": "wind", "rarity": "rare", "unlock": 2, "label": "Vent arrière", "short": "Même sens que le trait d'avant : +{v} m", "icon": "long_stroke", "trig": "stroke",
		"name": "Oikaze", "sub": "Vent arrière", "when": "TRAIT DANS LE MÊME SENS",
		"text": "Un trait tracé dans le sens du précédent est poussé par le vent : ta ruée continue plus loin, sans encre.",
		"stat": "Ruée prolongée de {v} m", "v": [1.5, 2.5, 3.5]},
	"wind_fujin": {"school": "wind", "rarity": "legendary", "unlock": 4, "label": "Dieu du vent", "short": "Aspire puis souffle · +{v} m", "icon": "cloud_gust", "trig": "stroke",
		"name": "Fūjin", "sub": "Dieu du vent", "kanji": "嵐", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Ton trait aspire les ennemis proches sur sa ligne, puis ton arrivée les souffle.",
		"stat": "Trait max +{v} m · encre +50 %", "v": [4]},

	# ---------------------------------------------------------------- OMBRE
	"shadow_back": {"school": "shadow", "rarity": "common", "unlock": 0, "label": "Dans le dos", "short": "Dans le dos : dégâts ×{v}", "icon": "backstab", "trig": "back",
		"name": "Ushiro", "sub": "Frappe dans le dos", "when": "DANS LE DOS",
		"text": "Frappe un ennemi dans le dos : tes dégâts sont multipliés.",
		"stat": "Dégâts ×{v} dans le dos", "v": [2.0, 2.5, 3.0]},
	"shadow_step": {"school": "shadow", "rarity": "common", "unlock": 0, "label": "Pas d'ombre", "short": "Invincible {v} s à l'arrivée", "icon": "footsteps", "trig": "arrive",
		"name": "Pas d'ombre", "sub": "Arrivée fantôme", "when": "QUAND TU ARRIVES",
		"text": "Après l'arrivée d'une ruée, rien ne peut te toucher pendant un court instant.",
		"stat": "Invincible {v} s", "v": [0.25, 0.4, 0.55]},
	"shadow_veil": {"school": "shadow", "rarity": "common", "unlock": 1, "label": "Voile", "short": "2 tués d'un trait : invincible {v} s", "icon": "hood", "trig": "kill",
		"name": "Voile", "sub": "Voile d'ombre", "when": "2 TUÉS D'UN TRAIT",
		"text": "Tue 2 ennemis ou plus d'un seul trait : tu deviens invincible un instant.",
		"stat": "Invincible {v} s", "v": [0.6, 0.9, 1.2]},
	"shadow_execute": {"school": "shadow", "rarity": "rare", "unlock": 1, "label": "Coup de grâce", "short": "Achève sous {v} % de vie", "icon": "skull", "trig": "target",
		"name": "Kaishaku", "sub": "Coup de grâce", "kanji": "斬",
		"when": "ENNEMI AFFAIBLI",
		"text": "Un ennemi presque mort est achevé net, d'un seul coup.",
		"stat": "Achève sous {v} % de vie", "v": [20, 25, 30]},
	"shadow_utsusemi": {"school": "shadow", "rarity": "epic", "unlock": 2, "label": "Leurre", "short": "Leurre : évite {v} coup/combat", "icon": "ghost", "trig": "hurt",
		"name": "Utsusemi", "sub": "Leurre d'ombre", "kanji": "逃",
		"when": "QUAND TU ES TOUCHÉ",
		"text": "Les premiers coups reçus par combat ne touchent qu'un leurre d'ombre, qui riposte.",
		"stat": "Évite {v}/combat · riposte : {w} dégâts", "v": [1, 1, 2], "w": [1.5, 2.5, 2.5]},
	"shadow_stolen": {"school": "shadow", "rarity": "epic", "unlock": 3, "label": "Instant volé", "short": "4 touchés : ralenti {v} s", "icon": "hourglass", "trig": "multi",
		"name": "Instant volé", "sub": "Ralenti", "when": "4 ENNEMIS D'UN TRAIT",
		"text": "Touche 4 ennemis d'un seul trait : le temps ralentit, vise bien le suivant.",
		"stat": "Ralenti : {v} s", "v": [0.8, 1.0, 1.2]},
	"shadow_double": {"school": "shadow", "rarity": "rare", "unlock": 2, "label": "Doublure", "short": "Une ombre reste au départ : estoc {w}", "icon": "clone", "trig": "stroke",
		"name": "Kagemusha", "sub": "Doublure d'ombre", "when": "À CHAQUE TRAIT",
		"text": "Une ombre reste à ton point de départ et poignarde le premier ennemi qui s'en approche.",
		"stat": "Attend {v} s · estoc : {w} dégâts", "v": [2.0, 2.5, 3.0], "w": [1.5, 2.0, 2.5]},
	"shadow_dusk": {"school": "shadow", "rarity": "rare", "unlock": 1, "label": "Crépuscule", "short": "1re touche sur chacun : ×{v}", "icon": "fx_crit", "trig": "hit",
		"name": "Tasogare", "sub": "Crépuscule", "when": "PREMIÈRE TOUCHE",
		"text": "Ta première touche sur chaque ennemi d'un combat est un coup critique.",
		"stat": "Premier coup ×{v}", "v": [1.4, 1.6, 1.8]},
	"shadow_bunshin": {"school": "shadow", "rarity": "legendary", "unlock": 4, "label": "Clone", "short": "Un clone refait tes traits", "icon": "clone", "trig": "stroke",
		"name": "Kage Bunshin", "sub": "Clone d'ombre", "kanji": "幻", "max": 1,
		"when": "À CHAQUE TRAIT",
		"text": "Un clone d'ombre refait chacun de tes traits juste après toi et frappe aussi.",
		"stat": "Clone : 1,2 dégât par ennemi touché", "v": [1]},
	"shadow_kitsunebi": {"school": "shadow", "rarity": "legendary", "unlock": 4, "label": "Feux follets", "short": "{v} feux follets autour de toi", "icon": "fox", "trig": "always",
		"name": "Kitsunebi", "sub": "Feux de renard", "kanji": "狐", "max": 1,
		"when": "EN PERMANENCE",
		"text": "Trois feux follets tournent autour de toi et brûlent les ennemis qu'ils touchent.",
		"stat": "{v} feux · 1 dégât par contact", "v": [3]},

	# ---------------------------------------------------------------- ENCRE (sans école)
	"ink_daruma": {"school": "ink", "rarity": "common", "unlock": 0, "label": "Daruma", "short": "+1 cœur max, soin {v}", "icon": "heart_plus", "trig": "now",
		"name": "Daruma", "sub": "Porte-bonheur", "when": "TOUT DE SUITE",
		"text": "Gagne 1 cœur max et soigne-toi tout de suite.",
		"stat": "+1 cœur max · soin : {v}", "v": [1, 1, 2]},
	"ink_thick": {"school": "ink", "rarity": "common", "unlock": 0, "label": "Encre épaisse", "short": "Taches au sol {v} s : ralentit", "icon": "one_stroke", "trig": "stroke",
		"name": "Nōboku", "sub": "Encre épaisse", "when": "À CHAQUE TRAIT",
		"text": "Ton trait laisse des taches d'encre au sol : les ennemis qui marchent dedans sont englués et ralentis.",
		"stat": "Taches {v} s · ennemis −40 % de vitesse", "v": [2.0, 2.5, 3.0]},
	"ink_seal": {"school": "ink", "rarity": "rare", "unlock": 2, "label": "Sceau", "short": "3 figures différentes : onde {v}", "icon": "stamp", "trig": "figure",
		"name": "Hanko", "sub": "Sceau d'encre", "when": "3 FIGURES DIFFÉRENTES",
		"text": "Trace trois figures différentes dans un même combat : le sceau claque, une onde d'encre repousse et étourdit.",
		"stat": "Onde : {v} dégâts à 3 m, étourdit", "v": [1.5, 2.0, 2.5]},
	"ink_omamori": {"school": "ink", "rarity": "rare", "unlock": 1, "label": "Talisman", "short": "Rouleaux rares +{v} %", "icon": "amulet", "trig": "luck",
		"name": "Omamori", "sub": "Talisman de chance", "when": "AUX ROULEAUX",
		"text": "Les rouleaux rares, épiques et légendaires sortent plus souvent.",
		"stat": "Chance +{v} % · +1 relance", "v": [30, 60, 90]},
	"ink_rakkan": {"school": "ink", "rarity": "epic", "unlock": 3, "label": "Sceau maître", "short": "+{v} pouvoir par école", "icon": "stamp", "trig": "school",
		"name": "Rakkan", "sub": "Sceau du maître", "max": 1, "when": "HARMONIE",
		"text": "Chaque école déjà commencée compte 1 pouvoir de plus pour ses bonus.",
		"stat": "+{v} pouvoir par école commencée", "v": [1]},
	"ink_enso": {"school": "ink", "rarity": "legendary", "unlock": 4, "label": "Ensō", "short": "Techniques : onde d'encre", "icon": "enso", "trig": "figure",
		"name": "Ensō parfait", "sub": "Cercle parfait", "kanji": "円", "max": 1,
		"when": "À CHAQUE TECHNIQUE",
		"text": "Chaque technique de figure lance une onde d'encre. L'onde de choc laisse un cercle d'encre.",
		"stat": "Onde : 1,5 dégât · onde de choc : +{v}", "v": [2],
		"needs": ["fig_loop", "fig_zigzag", "fig_straight", "fig_return", "fig_enso", "fig_hook", "fig_wave", "fig_point", "fig_triangle"]},
	"ink_ippitsu": {"school": "ink", "rarity": "legendary", "unlock": 4, "label": "Un seul trait", "short": "+{v} % par ennemi enchaîné", "icon": "one_stroke", "trig": "multi",
		"name": "Ippitsu", "sub": "Un seul trait", "kanji": "筆", "max": 1,
		"when": "À CHAQUE COUP",
		"text": "Chaque ennemi de plus touché d'un même trait prend plus cher. À 4 : trait suivant ×2.",
		"stat": "+{v} % par ennemi enchaîné", "v": [25]},

	# ---------------------------------------------------------------- FIGURES (techniques des formes tracées)
	# boucle
	"fig_loop": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Tourbillon", "short": "Boucle : toupie {v}/coup", "icon": "fig_loop", "trig": "figure",
		"name": "Uzu", "sub": "Tourbillon", "kanji": "渦", "when": "FIGURE : BOUCLE",
		"text": "Nouvelle technique sur ta boucle : quand tu traces une boucle, le héros tourne sur lui-même, aspire et lacère autour de lui.",
		"stat": "Toupie 0,8 s : {v} dégât par coup", "v": [0.45, 0.6, 0.75]},
	"fig_loop_pull": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Tourbillon aspirant", "short": "Toupie : aspire à {v} m", "icon": "fig_loop_pull", "trig": "figure",
		"name": "Uzumaki", "sub": "Tourbillon aspirant", "kanji": "渦", "max": 2, "when": "TECHNIQUE : TOUPIE",
		"text": "Ta toupie dure plus longtemps et aspire les ennemis de plus loin, bien plus fort.",
		"stat": "Aspiration : {v} m · toupie +0,3 s", "v": [4.5, 6.0], "needs": ["fig_loop"]},
	# zigzag
	"fig_zigzag": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Éclair en chaîne", "short": "Zigzag : foudre sur {v} ennemis", "icon": "fig_zigzag", "trig": "figure",
		"name": "Inazuma", "sub": "Éclair en chaîne", "kanji": "雷", "when": "FIGURE : ZIGZAG",
		"text": "Nouvelle technique sur ton zigzag : quand tu traces un zigzag, ta course accélère et la foudre saute d'ennemi en ennemi.",
		"stat": "Éclair : {v} ennemis, 1 dégât · course ×1,4", "v": [3, 4, 5]},
	"fig_zigzag_long": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Chaîne longue", "short": "Éclair : +{v} cibles", "icon": "fig_zigzag_long", "trig": "figure",
		"name": "Nagare", "sub": "Chaîne longue", "kanji": "雷", "max": 2, "when": "TECHNIQUE : ÉCLAIR",
		"text": "L'éclair de ton zigzag va plus loin et saute sur plus d'ennemis.",
		"stat": "+{v} ennemis foudroyés · portée +3 m", "v": [3, 5], "needs": ["fig_zigzag"]},
	# trait droit
	"fig_straight": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Iaï", "short": "Trait droit : coupe {v}", "icon": "fig_straight", "trig": "figure",
		"name": "Ittō", "sub": "Coupe iaï", "kanji": "一", "when": "FIGURE : TRAIT DROIT",
		"text": "Nouvelle technique sur ton trait droit : un long trait droit (tu le traces déjà) perce désormais les gardes, puis une coupe tombe sur toute la ligne.",
		"stat": "Coupe : {v} dégâts · course ×1,4", "v": [1.5, 1.8, 2.1]},
	"fig_straight_double": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Double coupe", "short": "Iaï : 2e coupe à {v} %", "icon": "fig_straight_double", "trig": "figure",
		"name": "Nitō", "sub": "Double coupe", "kanji": "一", "max": 2, "when": "TECHNIQUE : IAÏ",
		"text": "Une seconde coupe suit la première, un instant plus tard, sur la même ligne.",
		"stat": "2e coupe : {v} % des dégâts", "v": [60, 90], "needs": ["fig_straight"]},
	"fig_straight_wave": {"school": "fig", "rarity": "epic", "unlock": 2, "label": "Onde tranchante", "short": "Iaï : +{v} m, plus large", "icon": "fig_straight_wave", "trig": "figure",
		"name": "Zankō", "sub": "Onde tranchante", "kanji": "斬", "max": 2, "when": "TECHNIQUE : IAÏ",
		"text": "La coupe file au-delà de ton trait en onde tranchante, plus large et plus loin.",
		"stat": "Coupe prolongée de {v} m · largeur ×1,5", "v": [3, 5], "needs": ["fig_straight"]},
	# aller-retour
	"fig_return": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Garde", "short": "Aller-retour : garde {v} s", "icon": "fig_return", "trig": "figure",
		"name": "Kaeshi", "sub": "Garde", "kanji": "返", "when": "FIGURE : ALLER-RETOUR",
		"text": "Nouvelle technique sur ton aller-retour : après un aller-retour, tu te mets en garde et rien ne te touche.",
		"stat": "Garde : {v} s", "v": [0.5, 0.65, 0.8]},
	"fig_return_reflect": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Renvoi", "short": "Renvoie les tirs à {v} m", "icon": "fig_return_reflect", "trig": "figure",
		"name": "Hanekaeshi", "sub": "Renvoi des tirs", "kanji": "返", "max": 2, "when": "TECHNIQUE : GARDE",
		"text": "En traçant ton aller-retour, les tirs proches du trait repartent vers les ennemis.",
		"stat": "Portée du renvoi : {v} m", "v": [1.6, 2.4], "needs": ["fig_return"]},
	"fig_return_counter": {"school": "fig", "rarity": "epic", "unlock": 2, "label": "Contre", "short": "Garde : contre {v}", "icon": "fig_return_counter", "trig": "figure",
		"name": "Ōji", "sub": "Contre", "kanji": "返", "max": 2, "when": "TECHNIQUE : GARDE",
		"text": "Pendant ta garde, chaque ennemi qui prépare un coup près de toi est contré et étourdi.",
		"stat": "Contre : {v} dégâts, étourdit", "v": [2, 3], "needs": ["fig_return"]},
	# ensō
	"fig_enso": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Onde de choc", "short": "Ensō : bond et onde {v}", "icon": "fig_enso", "trig": "figure",
		"name": "Ensō", "sub": "Onde de choc", "kanji": "円", "when": "FIGURE : ENSŌ",
		"text": "Nouvelle technique sur ton ensō : quand tu traces un grand cercle presque fermé, le héros bondit au centre et frappe le sol.",
		"stat": "Onde de choc : {v} dégâts", "v": [1.5, 1.8, 2.1]},
	"fig_enso_big": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Grand ensō", "short": "Ensō : onde +{v} %", "icon": "fig_enso_big", "trig": "figure",
		"name": "Dai-ensō", "sub": "Grand cercle", "kanji": "円", "max": 2, "when": "TECHNIQUE : ONDE DE CHOC",
		"text": "Ton onde de choc porte plus loin et projette les ennemis bien plus fort.",
		"stat": "Rayon de l'onde +{v} %", "v": [30, 60], "needs": ["fig_enso"]},
	"fig_enso_heal": {"school": "fig", "rarity": "epic", "unlock": 3, "label": "Ensō de soin", "short": "Ensō : +{v} cœur par combat", "icon": "fig_enso_heal", "trig": "figure",
		"name": "Iyashi", "sub": "Ensō de soin", "kanji": "円", "max": 1, "when": "TECHNIQUE : ONDE DE CHOC",
		"text": "La première onde de choc de chaque combat te soigne.",
		"stat": "+{v} cœur, 1 fois par combat", "v": [1], "needs": ["fig_enso"]},
	# crochet
	"fig_hook": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Estoc", "short": "Crochet : estoc {v}", "icon": "fig_hook", "trig": "figure",
		"name": "Kagi", "sub": "Estoc", "kanji": "鉤", "when": "FIGURE : CROCHET",
		"text": "Nouvelle technique sur ton crochet : quand tu traces un crochet, le héros fait demi-tour et transperce l'ennemi le plus proche.",
		"stat": "Estoc : {v} dégâts", "v": [2.0, 2.5, 3.0]},
	"fig_hook_back": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Estoc assassin", "short": "Estoc ×{v} : blessé ou de dos", "icon": "fig_hook_back", "trig": "figure",
		"name": "Ansatsu", "sub": "Estoc assassin", "kanji": "背", "max": 2, "when": "TECHNIQUE : ESTOC",
		"text": "Ton estoc frappe bien plus fort un ennemi pris de dos ou déjà à moitié mort.",
		"stat": "Estoc ×{v} (de dos, ou sous 50 % de vie)", "v": [2.0, 2.5], "needs": ["fig_hook"]},
	"fig_hook_double": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Double estoc", "short": "Estoc : +{v} cible", "icon": "fig_hook_double", "trig": "figure",
		"name": "Nidan-zuki", "sub": "Double estoc", "kanji": "鉤", "max": 2, "when": "TECHNIQUE : ESTOC",
		"text": "Ton estoc transperce aussi les ennemis voisins de ta cible.",
		"stat": "+{v} ennemi transpercé", "v": [1, 2], "needs": ["fig_hook"]},
	# vague (figure de l'arbre)
	"fig_wave": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Ressac", "short": "Vague : ressac {v}", "icon": "fig_wave", "trig": "figure",
		"name": "Yosenami", "sub": "Ressac", "kanji": "波", "when": "FIGURE : VAGUE",
		"text": "Nouvelle technique sur ta vague : quand tu traces un S, une vague d'encre suit la courbe et repousse les ennemis vers l'extérieur.",
		"stat": "Ressac : {v} dégât, repousse", "v": [0.6, 0.8, 1.0]},
	"fig_wave_stun": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Lame de fond", "short": "Ressac : recul ×{v}, étourdit", "icon": "fig_wave_stun", "trig": "figure",
		"name": "Uneri", "sub": "Lame de fond", "kanji": "波", "max": 2, "when": "TECHNIQUE : RESSAC",
		"text": "Ta vague repousse bien plus loin et étourdit les ennemis qu'elle emporte.",
		"stat": "Recul ×{v} · étourdit", "v": [1.6, 2.2], "needs": ["fig_wave"]},
	# pointe (figure de l'arbre)
	"fig_point": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Kunai", "short": "Pointe : 3 kunai {v}", "icon": "fig_point", "trig": "figure",
		"name": "Kunai", "sub": "Kunai d'encre", "kanji": "刃", "when": "FIGURE : POINTE",
		"text": "Nouvelle technique sur ta pointe : quand tu traces un V, trois kunai d'encre partent de la pointe dans l'axe du V et percent toute la ligne.",
		"stat": "3 kunai : {v} dégât chacun, percent", "v": [0.9, 1.15, 1.4]},
	"fig_point_more": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Volée de kunai", "short": "Kunai : +{v}", "icon": "fig_point_more", "trig": "figure",
		"name": "Senbon", "sub": "Volée de kunai", "kanji": "刃", "max": 2, "when": "TECHNIQUE : KUNAI",
		"text": "Ta pointe lance plus de kunai, en éventail plus large.",
		"stat": "+{v} kunai", "v": [2, 4], "needs": ["fig_point"]},
	# triangle (figure de l'arbre)
	"fig_triangle": {"school": "fig", "rarity": "common", "unlock": 0, "label": "Kekkai", "short": "Triangle : sceau {v}", "icon": "fig_triangle", "trig": "figure",
		"name": "Kekkai", "sub": "Sceau triangulaire", "kanji": "結", "when": "FIGURE : TRIANGLE",
		"text": "Nouvelle technique sur ton triangle : quand tu traces un triangle fermé, un sceau se pose au sol 3 s ; les ennemis dedans sont figés, puis frappés quand il se referme.",
		"stat": "Sceau 3 s : fige, puis {v} dégâts", "v": [1.5, 2.0, 2.5]},
	"fig_triangle_long": {"school": "fig", "rarity": "rare", "unlock": 1, "label": "Grand sceau", "short": "Sceau : +{v} s, plus grand", "icon": "fig_triangle_long", "trig": "figure",
		"name": "Dai-kekkai", "sub": "Grand sceau", "kanji": "結", "max": 2, "when": "TECHNIQUE : KEKKAI",
		"text": "Ton sceau triangulaire tient plus longtemps et déborde un peu de ton tracé.",
		"stat": "Sceau +{v} s · taille ×1,3", "v": [1.0, 2.0], "needs": ["fig_triangle"]},
}

# Effet de chaque pouvoir en pastilles (cartes, bulle de détail, récapitulatif), sans répéter le nom du pouvoir.
# "fx" : rangées [pictogramme UiKit.glyph, valeur, libellé en 1-2 mots] ; la carte montre les 2 premières.
#   Valeur : « {v} » / « {w} » = valeur du niveau (tableaux v / w du pouvoir) ; « {v%} » / « {w%} » = dégâts en %
#   d'un coup de sabre (0,5 -> 50). Amélioration : « avant → après » (UiKit.fx_rows). Valeur vide : le libellé seul.
# "tw" : déclencheur en 1-2 mots (bulle) ; "line" : une phrase courte d'explication (bulle).
const EFFECTS := {
	# ---------------------------------------------------------------- FEU
	"fire_burn": {"fx": [["fire", "{v%} %/s", "brûlure"], ["hourglass", "3 s", "durée"]],
		"tw": "Chaque coup", "line": "Chaque ennemi tranché par ta ruée prend feu et brûle quelques secondes."},
	"fire_trail": {"fx": [["fire", "{v%} %/s", "feu au sol"], ["hourglass", "3 s", "durée"]],
		"tw": "Chaque trait", "line": "Chaque ruée laisse une ligne de feu au sol derrière toi, qui brûle les ennemis qui la traversent."},
	"fire_edge": {"fx": [["fx_dmg", "+{v} %", "dégâts"]],
		"tw": "Ennemi brûlé", "line": "Tes coups de sabre font plus de dégâts aux ennemis déjà en feu."},
	"fire_hearth": {"fx": [["fx_dmg", "{v%} %", "explosion"]],
		"tw": "À l'arrivée", "line": "À la fin de chaque ruée, un cercle de feu explose autour de toi et brûle les ennemis proches."},
	"fire_spark": {"fx": [["fx_dmg", "{v%} %", "explosion"]],
		"tw": "Brûlé tué", "line": "Quand un ennemi en feu meurt, il explose et enflamme ses voisins."},
	"fire_kasha": {"fx": [["fire", "{v%} %/s", "dégâts"]],
		"tw": "Toupie", "line": "Quand tu traces une boucle, ta toupie lance une roue de feu qui brûle les ennemis autour."},
	"fire_fudo": {"fx": [["fire", "{v%} %/s", "brûlure"]],
		"tw": "Permanent", "line": "En permanence, un halo de flammes t'entoure : tout ennemi qui s'approche prend feu."},
	"fire_ash": {"fx": [["hourglass", "{v} s", "cendres"], ["fire", "", "enflamme"]],
		"tw": "Brûlé tué", "line": "Quand un ennemi en feu meurt, ses cendres restent au sol : tout ennemi qui les traverse prend feu."},
	"fire_lantern": {"fx": [["fx_dmg", "80 %", "gerbe"], ["clock", "{v} s", "rythme"]],
		"tw": "Automatique", "line": "À intervalle régulier, l'ennemi en feu le plus proche s'embrase : la gerbe brûle et enflamme ses voisins."},
	"fire_hoo": {"fx": [["fx_heart", "{v}", "cœurs au retour"], ["fx_dmg", "+25 %", "dégâts"]],
		"tw": "1 fois", "line": "+1 cœur maximum. Une fois par partie, le coup qui devait te tuer te fait renaître."},
	# ---------------------------------------------------------------- EAU
	"water_push": {"fx": [["push_wave", "{v} m", "recul"]],
		"tw": "Chaque coup", "line": "Chaque ennemi tranché par ta ruée est projeté loin de ton trait."},
	"water_dew": {"fx": [["fx_heart", "+1", "cœur"], ["skull", "{v}", "ennemis tués"]],
		"tw": "En tuant", "line": "Chaque fois que tu tues plusieurs ennemis d'affilée, tu regagnes 1 cœur."},
	"water_foam": {"fx": [["shield", "{v}/combat", "coup bloqué"], ["fx_dmg", "{w%} %", "éclat"]],
		"tw": "Si touché", "line": "Quand un ennemi te touche, une bulle d'eau encaisse le coup à ta place, puis éclate sur les ennemis proches."},
	"water_tide": {"fx": [["tide", "{v%} %", "vague"]],
		"tw": "À l'arrivée", "line": "À la fin de chaque ruée, une vague jaillit autour de toi et repousse les ennemis."},
	"water_uzushio": {"fx": [["fx_dmg", "{v%} %/s", "dégâts"], ["hourglass", "3 s", "durée"]],
		"tw": "3 touchés", "line": "Quand une ruée touche 3 ennemis ou plus, un tourbillon s'ouvre à l'arrivée et aspire les ennemis dedans."},
	"water_mirror": {"fx": [["fx_range", "{v} m", "renvoi"]],
		"tw": "Pendant le trait", "line": "Pendant ta ruée, les tirs que tu frôles sont renvoyés vers l'ennemi qui les a lancés."},
	"water_mist": {"fx": [["hourglass", "{v} s", "brume"], ["fx_radius", "2,3 m", "rayon"]],
		"tw": "À l'arrivée", "line": "À la fin de chaque ruée, une brume reste autour de ton arrivée : les tirs qui la traversent se dissolvent."},
	"water_spring": {"fx": [["fx_heart", "+1", "cœur"], ["hourglass", "{v}", "combats"]],
		"tw": "À l'arrivée", "line": "Si tu as perdu un cœur, l'arrivée de ta ruée te soigne : une fois tous les quelques combats."},
	"water_kanagawa": {"fx": [["fx_dmg", "{v%} %", "déferlante"], ["shield", "+1", "bulle/combat"]],
		"tw": "3 traits", "line": "Tous les 3 traits, une énorme vague déferle le long de ta ruée et balaie les ennemis."},
	# ---------------------------------------------------------------- FOUDRE
	"bolt_arc": {"fx": [["chain_bolt", "+{v}", "cibles"], ["fx_dmg", "50 %", "dégâts"]],
		"tw": "Chaque coup", "line": "À chaque coup de sabre, un éclair saute de ta cible vers les ennemis proches."},
	"bolt_quick": {"fx": [["speed", "+{v} %", "course"]],
		"tw": "Permanent", "line": "En permanence, tu cours plus vite le long du trait : tu restes moins longtemps exposé."},
	"bolt_charge": {"fx": [["bolt", "{v%} %/m", "foudre"]],
		"tw": "À l'arrivée", "line": "À la fin de chaque ruée, la foudre frappe l'arrivée : plus le trait était long, plus elle frappe fort."},
	"bolt_storm": {"fx": [["bolt", "100 %", "3 cibles"], ["t_hit", "{v}", "coups"]],
		"tw": "En frappant", "line": "Chaque coup de sabre charge le ciel : après plusieurs coups, la foudre tombe sur tes ennemis."},
	"bolt_thunder": {"fx": [["fx_dmg", "+{v%} %", "dégâts"], ["stun", "", "étourdit"]],
		"tw": "3 touchés", "line": "Dès le 3e ennemi tranché dans une même ruée, chaque coup suivant étourdit sa cible."},
	"bolt_raiju": {"fx": [["fx_dmg", "200 %", "morsure"], ["clock", "{v} s", "rythme"]],
		"tw": "Automatique", "line": "Un loup de foudre t'accompagne : il mord et étourdit l'ennemi le plus proche de lui-même."},
	"bolt_inazuma": {"fx": [["fx_dmg", "+{v%} %", "par cible"], ["stun", "", "étourdit"]],
		"tw": "Éclair", "line": "Quand tu traces un zigzag, l'éclair paralyse chaque ennemi qu'il touche."},
	"bolt_rod": {"fx": [["bolt", "100 %", "foudre"], ["stun", "", "interrompt"], ["clock", "{v} s", "recharge"]],
		"tw": "Attaque proche", "line": "Quand un ennemi proche prépare un coup, la foudre tombe sur lui et interrompt son attaque."},
	"bolt_static": {"fx": [["fx_dmg", "{v%} %", "nova"], ["t_stroke", "4", "traits"], ["stun", "", "étourdit"]],
		"tw": "4 traits", "line": "Chaque trait te charge ; à l'arrivée du 4e, une nova électrique frappe et étourdit tout autour de toi."},
	"bolt_raijin": {"fx": [["chain_bolt", "{v}", "foudroyés"], ["fx_dmg", "200 %", "tous les 4 traits"]],
		"tw": "Chaque coup", "line": "Tous les 4 traits, un coup de tambour frappe et repousse tous les ennemis qui t'attaquent."},
	# ---------------------------------------------------------------- VENT
	"wind_long": {"fx": [["long_stroke", "+{v} m", "trait max"]],
		"tw": "Permanent", "line": "En permanence, ta jauge d'encre est plus longue : tu peux tracer des traits plus longs."},
	"wind_gust": {"fx": [["refill", "+{v} %", "recharge"]],
		"tw": "Permanent", "line": "En permanence, ton encre se recharge plus vite entre deux traits."},
	"wind_feather": {"fx": [["long_stroke", "{v} m", "sans encre"]],
		"tw": "Chaque trait", "line": "Les premiers mètres de chaque trait ne vident pas ta jauge d'encre : tu pars plus léger."},
	"wind_blades": {"fx": [["fx_dmg", "{v%} %", "en courant"]],
		"tw": "Pendant le trait", "line": "Pendant ta ruée, des lames de vent tranchent les ennemis qui longent ton trait."},
	"wind_tsumuji": {"fx": [["fx_dmg", "{v%} %", "tourbillon"], ["tornado", "2", "par ruée"]],
		"tw": "Chaque trait", "line": "À chaque ruée, un tourbillon tranchant frappe les ennemis à ton départ, puis un autre à ton arrivée."},
	"wind_stillness": {"fx": [["clock", "{v} s", "temps lent"], ["hourglass", "5 s", "recharge"]],
		"tw": "Doigt posé", "line": "Dès que tu poses le doigt, le temps ralentit un instant pour que tu vises."},
	"wind_gale": {"fx": [["fx_radius", "{v} m", "souffle"], ["push_wave", "", "tirs repoussés"]],
		"tw": "Pendant le trait", "line": "Pendant ta ruée, les tirs qui passent près de toi sont soufflés au loin et ne te touchent pas."},
	"wind_current": {"fx": [["fx_range", "+{v} m", "ruée"], ["t_stroke", "", "même sens"]],
		"tw": "Même sens", "line": "Quand ton trait part dans le sens du précédent, le vent te pousse : la ruée continue plus loin, gratuitement."},
	"wind_fujin": {"fx": [["long_stroke", "+{v} m", "trait max"], ["refill", "+50 %", "encre"]],
		"tw": "Chaque trait", "line": "Pendant ta ruée, les ennemis sont aspirés vers ton trait ; à l'arrivée, ils sont soufflés au loin."},
	# ---------------------------------------------------------------- OMBRE
	"shadow_back": {"fx": [["backstab", "×{v}", "dégâts"]],
		"tw": "De dos", "line": "Quand tu tranches un ennemi de dos, les dégâts sont multipliés."},
	"shadow_step": {"fx": [["shield", "{v} s", "invincible"]],
		"tw": "À l'arrivée", "line": "Juste après l'arrivée de chaque ruée, tu deviens intouchable un court instant."},
	"shadow_veil": {"fx": [["shield", "{v} s", "invincible"]],
		"tw": "2 tués", "line": "Quand tu tues 2 ennemis dans une même ruée, tu deviens intouchable un court instant."},
	"shadow_execute": {"fx": [["skull", "< {v} %", "achève"]],
		"tw": "Affaibli", "line": "Quand tu touches un ennemi presque mort, il tombe d'un seul coup."},
	"shadow_utsusemi": {"fx": [["ghost", "{v}/combat", "coup évité"], ["fx_dmg", "{w%} %", "riposte"]],
		"tw": "Si touché", "line": "Quand un ennemi te touche, un leurre d'ombre prend le coup à ta place, puis riposte."},
	"shadow_stolen": {"fx": [["clock", "{v} s", "ralenti"]],
		"tw": "4 touchés", "line": "Quand une ruée touche 4 ennemis, le temps ralentit : tu as le temps de viser le suivant."},
	"shadow_double": {"fx": [["fx_dmg", "{w%} %", "estoc"], ["hourglass", "{v} s", "attente"]],
		"tw": "Chaque trait", "line": "Une ombre reste là où ta ruée est partie ; le premier ennemi qui s'en approche reçoit un coup d'estoc."},
	"shadow_dusk": {"fx": [["fx_crit", "×{v}", "1re touche"]],
		"tw": "1re touche", "line": "La première fois que tu tranches un ennemi dans un combat, le coup est critique."},
	"shadow_bunshin": {"fx": [["fx_dmg", "120 %", "par ennemi"]],
		"tw": "Chaque trait", "line": "Après chaque ruée, une ombre refait ton trait et tranche à son tour les ennemis."},
	"shadow_kitsunebi": {"fx": [["fire", "{v}", "flammes"], ["fx_dmg", "100 %", "par contact"]],
		"tw": "Permanent", "line": "En permanence, des feux follets tournent autour de toi et brûlent les ennemis qu'ils touchent."},
	# ---------------------------------------------------------------- ENCRE
	"ink_daruma": {"fx": [["heart_plus", "+1", "cœur max"], ["fx_heart", "+{v}", "soin"]],
		"tw": "Immédiat", "line": "Tout de suite : +1 cœur maximum, et tous tes cœurs sont soignés."},
	"ink_thick": {"fx": [["speed", "-40 %", "ennemis"], ["hourglass", "{v} s", "taches"]],
		"tw": "Chaque trait", "line": "Ton trait laisse des taches d'encre au sol : les ennemis qui marchent dedans sont englués et ralentis."},
	"ink_seal": {"fx": [["fx_dmg", "{v%} %", "onde"], ["t_figure", "3", "figures différentes"], ["stun", "", "étourdit"]],
		"tw": "3 figures", "line": "Trace trois figures différentes dans un même combat : le sceau claque, une onde d'encre repousse et étourdit."},
	"ink_omamori": {"fx": [["star", "+{v} %", "rareté"], ["reroll", "+1", "relance"]],
		"tw": "Rouleaux", "line": "Dans les prochains choix de rouleaux, les pouvoirs rares apparaissent plus souvent."},
	"ink_rakkan": {"fx": [["stamp", "+{v}", "par école"]],
		"tw": "Harmonie", "line": "Pour l'harmonie, chaque élément que tu as commencé compte un pouvoir de plus."},
	"ink_enso": {"fx": [["fx_dmg", "150 %", "onde d'encre"], ["fig_enso", "+{v%} %", "onde de choc"]],
		"tw": "Technique", "line": "Chaque technique de figure (toupie, éclair, iaï…) lance en plus une onde d'encre qui blesse les ennemis."},
	"ink_ippitsu": {"fx": [["t_multi", "+{v} %", "par ennemi"], ["fx_crit", "×2", "à 4 touchés"]],
		"tw": "Enchaîné", "line": "Dans une même ruée, chaque ennemi tranché après le premier prend plus de dégâts que le précédent."},
	# ---------------------------------------------------------------- FIGURES
	"fig_loop": {"fx": [["fx_dmg", "{v%} %", "par coup"], ["hourglass", "0,8 s", "toupie"]],
		"tw": "Boucle", "line": "Quand tu traces une boucle, le héros tourne sur lui-même à l'arrivée et lacère tout autour."},
	"fig_loop_pull": {"fx": [["fx_pull", "{v} m", "attraction"], ["hourglass", "+0,3 s", "toupie"]],
		"tw": "Toupie", "line": "Ta toupie (boucle) attire les ennemis de plus loin et dure plus longtemps."},
	"fig_zigzag": {"fx": [["chain_bolt", "{v}", "cibles"], ["speed", "×1,4", "course"], ["fx_dmg", "100 %", "par cible"]],
		"tw": "Zigzag", "line": "Quand tu traces un zigzag, ta course accélère et la foudre saute d'ennemi en ennemi."},
	"fig_zigzag_long": {"fx": [["chain_bolt", "+{v}", "cibles"], ["fx_range", "+3 m", "portée"]],
		"tw": "Éclair", "line": "Ton éclair (zigzag) porte plus loin et saute sur plus d'ennemis."},
	"fig_straight": {"fx": [["fx_dmg", "{v%} %", "coupe"], ["speed", "×1,4", "course"]],
		"tw": "Trait droit", "line": "Quand tu traces un long trait droit, l'iaï perce les gardes et les boucliers, puis tranche."},
	"fig_straight_double": {"fx": [["fx_dmg", "{v} %", "2e frappe"]],
		"tw": "Iaï", "line": "Après chaque iaï (trait droit), une seconde coupe suit un instant plus tard."},
	"fig_straight_wave": {"fx": [["fx_range", "+{v} m", "portée"], ["fx_radius", "×1,5", "largeur"]],
		"tw": "Iaï", "line": "Ton iaï (trait droit) continue de couper au-delà de la fin du trait."},
	"fig_return": {"fx": [["shield", "{v} s", "invulnérable"]],
		"tw": "Aller-retour", "line": "Après un aller-retour, tu deviens intouchable un court instant."},
	"fig_return_reflect": {"fx": [["fx_range", "{v} m", "tirs retournés"]],
		"tw": "Aller-retour", "line": "Après un aller-retour, les tirs proches de ton trait sont renvoyés à l'envoyeur."},
	"fig_return_counter": {"fx": [["fx_dmg", "{v%} %", "riposte"], ["stun", "", "étourdit"]],
		"tw": "Garde", "line": "Tant que tu es en garde (aller-retour), chaque attaque proche est contrée."},
	"fig_enso": {"fx": [["fx_dmg", "{v%} %", "onde de choc"]],
		"tw": "Ensō", "line": "Quand tu traces un grand cercle, le héros bondit au centre et frappe le sol : une onde de choc."},
	"fig_enso_big": {"fx": [["fx_radius", "+{v} %", "rayon"], ["push_wave", "×2", "recul"]],
		"tw": "Ensō", "line": "Ton onde de choc (ensō) porte plus loin et projette les ennemis plus fort."},
	"fig_enso_heal": {"fx": [["fx_heart", "+{v}", "cœur/combat"]],
		"tw": "Ensō", "line": "La première onde de choc (ensō) de chaque combat te soigne."},
	"fig_hook": {"fx": [["fx_dmg", "{v%} %", "transperce"]],
		"tw": "Crochet", "line": "Quand tu traces un crochet, le héros fait demi-tour et transperce l'ennemi le plus proche."},
	"fig_hook_back": {"fx": [["backstab", "×{v}", "de dos"], ["skull", "×{v}", "sous 50 % vie"]],
		"tw": "Crochet", "line": "Ton estoc (crochet) fait bien plus de dégâts sur un ennemi de dos ou déjà blessé."},
	"fig_hook_double": {"fx": [["t_multi", "+{v}", "cibles"]],
		"tw": "Crochet", "line": "Ton estoc (crochet) transperce aussi les ennemis voisins de ta cible."},
	"fig_wave": {"fx": [["fx_dmg", "{v%} %", "vague"], ["push_wave", "", "repousse"]],
		"tw": "Vague", "line": "Quand tu traces un S, une vague d'encre suit la courbe et repousse les ennemis vers l'extérieur."},
	"fig_wave_stun": {"fx": [["push_wave", "×{v}", "recul"], ["stun", "", "étourdit"]],
		"tw": "Ressac", "line": "Ta vague (S) repousse plus loin et étourdit les ennemis qu'elle emporte."},
	"fig_point": {"fx": [["fx_dmg", "{v%} %", "par kunai"], ["t_multi", "3", "kunai"]],
		"tw": "Pointe", "line": "Quand tu traces un V, trois kunai d'encre partent de la pointe et percent la ligne d'ennemis."},
	"fig_point_more": {"fx": [["t_multi", "+{v}", "kunai"]],
		"tw": "Kunai", "line": "Ta pointe (V) lance plus de kunai, en éventail plus large."},
	"fig_triangle": {"fx": [["fx_dmg", "{v%} %", "fermeture"], ["hourglass", "3 s", "figés"]],
		"tw": "Triangle", "line": "Quand tu traces un triangle fermé, un sceau fige les ennemis dedans, puis les frappe en se refermant."},
	"fig_triangle_long": {"fx": [["hourglass", "+{v} s", "sceau"], ["fx_radius", "×1,3", "taille"]],
		"tw": "Kekkai", "line": "Ton sceau (triangle) tient plus longtemps et déborde un peu de ton tracé."},
}
